scholia/app/templates/venue_empty.html
added a few more examples from different fields, reordered alphabetically.
There is also a list of the journals most cited on the English Wikipedia: https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Academic_Journals/Journals_cited_by_Wikipedia/Popular1 .
=> some more examples for journals

scholia/app/templates/topic_empty.html
=> two more examples

scholia/app/templates/work_empty.html
Got them via [this modified query](https://query.wikidata.org/#PREFIX%20pr%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Freference%2F%3E%0APREFIX%20prov%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fprov%23%3E%0A%0ASELECT%20DISTINCT%20%3Fpaper%20%28COUNT%28%3Fstatement%29%20AS%20%3Fcount%29%20WHERE%20%7B%0A%20%20%3Fstatement%20%28prov%3AwasDerivedFrom%2Fpr%3AP248%29%20%3Fpaper.%0A%20%20%3Fotherpaper%20wdt%3AP2860%20%3Fpaper.%0A%20%20%3Fpaper%20wdt%3AP31%20wd%3AQ13442814.%0A%7D%0AGROUP%20BY%20%3Fpaper%20%0AORDER%20BY%20DESC%28%3Fcount%29). The top 200 ones or so time out, so I went for some middle ground.
=> richer examples

scholia/app/templates/organization_empty.html
=> Organization examples

scholia/app/templates/venue.html
Is there an easy way for me to test this locally?
=> Updated to use the new design: most cited works in venue

scholia/app/templates/topic.html
I hope I got all right this time around :)
=> Updated to the new query style

scholia/app/templates/topic.html
Per request: https://twitter.com/pigsonthewing/status/875411864422932480
=> Include ORCIDs for authors

scholia/app/static/scholia.js, scholia/app/templates/base.html, scholia/app/templates/chemical.html, scholia/app/templates/chemical_base.html, scholia/app/templates/chemical_empty.html, scholia/app/views.py
Which lists for the chemical the external identifiers, similar compounds, and the physchem properties.
=> Adds a topic section 'chemical'

scholia/app/templates/work.html
=> Migrated another query to the new code design

scholia/app/templates/organization.html, scholia/app/templates/publisher.html
A few more patches to review...
=> More updates: ORCID in 'organization' and two patches to migrate to new query approach

scholia/app/views.py, scholia/query.py
To support https://tools.wmflabs.org/scholia/cas/50-00-0
=> Implemented cas-to-q

scholia/app/templates/pathway.html
Instead of recent articles that cite this article, an idea I am pondering right now.
=> Because the list of papers is that with those of cited articles.

scholia/app/templates/index.html, scholia/app/views.py, scholia/query.py
Example link: http://127.0.0.1:5000/viaf/59976288
=> Adds VIAF support, to look up authors by their VIAF identifier.

scholia/app/templates/chemical_empty.html
=> CAS example + better InChI example description

scholia/app/views.py, scholia/rss.py, scholia/wikipedia.py
Adds RSS feeds for author, venue, and topic. This is a full draft and ready to be tested. If working, we can discuss adding RSS icons or links somewhere on the respective author, venue, and topic pages. Just add /latest/rss after /author/Qsomething...
For example:
=> RSS Feature

scholia/app/templates/taxon.html, scholia/app/templates/taxon_base.html, scholia/app/templates/taxon_empty.html, scholia/app/views.py, scholia/query.py
=> Feature to view taxons

scholia/query.py
Small patch, and maybe there are reasons why it is not like this? If so, please ignore.
=> Chapters are also works

scholia/query.py
$ python -m scholia.query q-to-class Q47501229
event
=> Detect event types

scholia/app/templates/author.html, scholia/app/templates/base.html
Which makes it look like:
@fnielsen, if you are OK, I can add an icon later...
=> Show the ORCID for authors (if available)

scholia/app/static/scholia.js, scholia/app/templates/index.html
to avoid having to click next
as requested by @Daniel-Mietchen to address #376
=> increase the statistics table page length

scholia/app/templates/chemical_class_empty.html, scholia/app/templates/chemical_empty.html
=> New layout for empty chemical / - class pages

scholia/app/templates/project.html, scholia/app/templates/project_base.html, scholia/app/templates/project_empty.html, scholia/app/views.py, scholia/query.py
I will steal Egon's work and work from that.
=> Project aspect

scholia/app/templates/project_empty.html
Small patch, but I like the new design.
=> Use columns

scholia/app/templates/author_empty.html
Patch for https://github.com/fnielsen/scholia/issues/487
=> Three column layout (closes #487)

scholia/query.py
=> Recognize 'group of chemical substances' as 'chemical-class' 

scholia/app/templates/publisher_empty.html
Related to the petition to ask them to join the I4OC: https://www.change.org/p/asking-the-american-chemical-society-to-join-the-initiative-for-open-citations
=> Added the ACS

scholia/app/templates/chemical_empty.html
Perhaps too slow for your taste? The two queries with links to literature take 1.5~ish secs each... but it cached (for a short time).
=> More statistics about chemicals (implements #547)

scholia/app/templates/chemical.html, scholia/app/templates/chemical_class.html
Small fix. Phenotype (on [this page](https://tools.wmflabs.org/scholia/chemical/Q161285)):
=> No duplicate topics

scholia/app/templates/work_empty.html, scholia/app/views.py, scholia/query.py
=> Added a redirect based on a PubMed identifier

scholia/app/templates/chemical.html
I think further replacement may me needed, and this approach can also be used for other properties (think SMILES) later.
=> Fixed linking out to JSmol for some InChIs (fixes #391)

scholia/app/templates/sponsor.html, scholia/app/views.py, scholia/rss.py
=> Implemented an RSS feed for recent papers funded by some sponsor 

scholia/app/templates/chemical_class_empty.html, scholia/app/templates/chemical_empty.html, scholia/app/views.py, scholia/query.py
=> Support for LIPID MAPS in redirects

scholia/app/views.py, scholia/query.py
Implements https://github.com/fnielsen/scholia/issues/728
=> Support (CLI and redirect) for the Research Organization Registry identifier

scholia/app/templates/chemical_element_empty.html, scholia/app/views.py, scholia/query.py
See https://goldbook.iupac.org/terms/view/A00503
=> Fix the name of atomic symbols

scholia/tex.py
=> Ensure extracted QIDs are valid

scholia/app/templates/clinical_trial.html
ClinWiki link in clinical-trial aspect based on ClinicalTrials.gov
=> Implement ClinWiki link #911

scholia/app/templates/pathway.html
Ok. Starting with a clean, rebased master, this patch only contains whitespace fixes, following the example by @fnielsen. There are no new features in this PR; just setting a clean background for this template.
=> code style fixes only

scholia/app/templates/event_series.html
Person table in the event-series aspect
=> Implement event-series person panel #921

scholia/app/templates/index.html
I have reworked the stats table to remain within the character limit for the SPARQL endpoint, as per #336 and https://github.com/Daniel-Mietchen/ideas/issues/1022 .
=> more stats on homepage, as per #336

scholia/app/templates/event_series_empty.html
Add table to the event series index page
=> Add event series table #958

scholia/app/templates/venue.html
=> added co-author graph to venue aspect

scholia/app/templates/topic.html
Adds an award panel to the topic aspect, thereby closing #661 .
=> adding award panel to topic aspect

scholia/app/templates/author_missing.html
I added sorting to the results table, so as to help prioritize curation.
=> sorted missing topics panel on missing author page

scholia/app/templates/award_missing.html
=> for #844: added an author query for missing page of award aspect

scholia/app/templates/award_missing.html
Fixes #845 and also addresses #972.
=> Add "missing topics" panel to award missing page

scholia/app/templates/topic.html, scholia/app/templates/topic_missing.html
Adds the following panels:
- for the topic aspect: 
- a panel on Earliest published works on the topic
- for the /missing page of the topic aspect:
- a panel on missing publication dates
- a panel on missing publication venues
=> 3 more panels for topics

scholia/app/templates/work.html
Hi,
I wanted to try out some SPARQL queries and I think I managed to implement the request in [issue 1043](https://github.com/fnielsen/scholia/issues/1043) with this pull request.
I also tested it locally and looked at a few example works. The tests with tox failed the same way as they did right after cloning, so I thought that's good enough.
=> Add most cited authors (solves issue #1043)

scholia/app/templates/topic.html, scholia/app/templates/topics.html
=> turned strings into links in topic and topics profiles

scholia/app/templates/venue_missing.html
Solves the link problem reported in #803
=> linkPrefixes fix for #803

scholia/app/templates/topic.html
=> fixes novalue issue as per #1080

scholia/app/templates/topic.html, scholia/app/templates/topics.html
=> added linkPrefixes for topic and topics pages

scholia/app/templates/topic_missing.html
also fixed the linkPrefixes, as per #1078
=> additional panel for works with missing co-topics, for /missing page in topic aspect

README.rst, scholia/app/templates/about.html, scholia/app/templates/author_missing.html, scholia/app/templates/award_missing.html, scholia/app/templates/faq.html, scholia/app/templates/organization_missing.html, scholia/app/templates/topic_missing.html, scholia/app/templates/venue_missing.html, scholia/app/templates/work.html, scholia/rss.py, scholia/text.py, scholia/wikipedia.py
=> Use the new URL scheme

scholia/app/templates/404_chemical.html, scholia/app/views.py
Implements https://github.com/fnielsen/scholia/issues/787
=> InChIKey not found page

scholia/app/templates/index.html
The tagline can be changed and is a suggestion.
Suggested by @chris-evelo
=> Added a short tagline to the front page

scholia/app/templates/topics.html
changed "List of works" to "List of works on any combination of these topics" in topic comparison
=> fixes #1137

scholia/app/templates/about.html
=> List funding in the Acks section

scholia/app/templates/base.html, scholia/app/templates/chemical.html, scholia/app/templates/gene.html, scholia/app/templates/protein.html
Okay, more than this won't happen tonight anymore.
=> Added more Bioschemas annotation

scholia/app/templates/topic.html
Attaching a screenshot from local version of https://tools.wmflabs.org/scholia/topic/Q101991 .
=> fixes #630 - add LIMIT to venuesSparql in topic aspect

scholia/app/templates/404_chemical.html
Brings down the query time from around 40 seconds to just under 15 seconds.
=> Faster query

scholia/app/templates/taxon.html
Implementation for https://github.com/fnielsen/scholia/issues/297
=> Added a table with identifiers

scholia/app/static/css/scholia.css
improving gui / fixing H3 size  #1128
=> improving gui / fixing H3 #1128 

scholia/app/templates/chemical.html
Addresses https://github.com/fnielsen/scholia/issues/1070
=> Better column names

scholia/app/views.py, scholia/query.py
This commit also change the name of the functions introducting an
underscore
=> Fix #1198: doctest now works for ncbi queries

scholia/app/templates/work.html
Not sure what linguistically is more correct, but mentions sounds better (to me). Finn, I leave it to your discretion.
=> Mentions or mentionings?

scholia/app/templates/work.html
Show publication in work aspect data table.
=> Show publication date for work #1226

scholia/app/static/scholia.js, scholia/app/templates/cito.html, scholia/app/templates/cito_base.html, scholia/app/templates/cito_empty.html, scholia/app/templates/venue_cito.html, scholia/app/views.py
Patch that will introduce CiTO data visualisation, where useful. First feature, CiTO data for a venue:
=> Added a first CiTO view, for venues, with landing page, and pages for CiTO intentions

scholia/app/templates/author.html
=> added co-author map to author profile

scholia/app/templates/base.html
=> Added Mastodon support to the author aspect

scholia/qs.py, scholia/scrape/ojs.py
Fix error when the title is empty #1230
Fix error when non-DC metafields not present #1255 #1203 #1223
Fix wrong selection of language for title #1202
Fix handling of year-only dates #1237
=> Fix OJS scraping

scholia/app/templates/author_missing.html, scholia/app/templates/award_missing.html, scholia/app/templates/organization_missing.html, scholia/app/templates/topic_missing.html, scholia/app/templates/venue_missing.html, scholia/app/templates/work.html
=> Use the oAuth disambiguator, per issue #1242

scholia/app/templates/work.html
Editors, reviewers, series and homepage have been added.
=> Implement extra field in work table #1259

scholia/app/templates/location-topic_nearby-researchers.sparql, scholia/app/templates/location.html, scholia/app/templates/location_nearby-locations-as-topics-in-works.sparql, scholia/app/templates/location_nearby-organizations.sparql, scholia/app/templates/location_topic.html
Here is converted location and location-topic, but not country.
One panel in location "Nearby locations as topics in works" seems to
time out and should be improved.
On the location-topic aspect the SPARQL query has been improved
for query time performance with and wikibase:around SERVICE query.
=> Convert location aspects to external SPARQL #1281

.gitignore
Isolated patch from https://github.com/fnielsen/scholia/pull/907
=> Add jetbrains folder to gitignore

scholia/app/templates/cito_empty.html
- split the number of annotations from the number of annotated citations
- number of articles cited with CiTO annotation
- number of journals cited with CiTO annotation
=> Added more CiTO statistics

scholia/app/templates/chemical_class.html, scholia/app/templates/chemical_class_class-hierarchy.sparql, scholia/app/templates/chemical_class_identifiers.sparql, scholia/app/templates/chemical_class_publications-per-year.sparql, scholia/app/templates/chemical_class_recent-literature.sparql, scholia/app/templates/chemical_class_related-chemicals.sparql
Implements another 1/3rd of https://github.com/fnielsen/scholia/issues/1270
=> External SPARQL for the chemical class aspect

scholia/app/templates/chemical_element.html, scholia/app/templates/chemical_element_allotropes.sparql, scholia/app/templates/chemical_element_isotopes.sparql, scholia/app/templates/chemical_element_recent-literature.sparql
Implements another 1/3rd of https://github.com/fnielsen/scholia/issues/1270
=> External SPARQL for the chemical element aspect

scholia/app/templates/base.html
Currently, for two `P31`:
* JRC representative nanomaterial: Q47461491
* nanomaterial: Q967847
=> Add Bioschemas for chemical substances #BioHackEU20

scholia/app/templates/taxon.html, scholia/app/templates/taxon_proteome.sparql
DO NOT APPLY UNTIL AFTER https://github.com/fnielsen/scholia/pull/1301
Implements https://github.com/fnielsen/scholia/issues/1299
=> Added a `taxon` proteome section

scholia/app/templates/taxon_metabolome.sparql
DO NOT APPLY TO MASTER BEFORE https://github.com/fnielsen/scholia/pull/1301
it adds a few more chemical groups that can be reported to be `found in taxon`. Implements https://github.com/fnielsen/scholia/issues/1300
=> List more metabolites

scholia/app/templates/base.html
Fixes https://github.com/fnielsen/scholia/issues/1310
=> Fixed matching of classes

scholia/app/templates/work.html
=> oauth link for Author Disambiguator work page - fixes #1319

scholia/app/templates/publisher.html, scholia/app/templates/publisher_citations-works.sparql, scholia/app/templates/publisher_editor-photos.sparql, scholia/app/templates/publisher_editors.sparql, scholia/app/templates/publisher_journals.sparql, scholia/app/templates/publisher_most-cited.sparql, scholia/app/templates/publisher_timeline.sparql
* implements https://github.com/fnielsen/scholia/issues/1277
* adds support for editor-in-chief
=> externalizes SPARQL queries for the publisher aspect

scholia/app/templates/event.html, scholia/app/templates/event_co-authors.sparql, scholia/app/templates/event_empty.html, scholia/app/templates/event_future-events.sparql, scholia/app/templates/event_past-events.sparql, scholia/app/templates/event_people.sparql, scholia/app/templates/event_proceedings.sparql, scholia/app/templates/event_recent-publications.sparql, scholia/app/templates/event_related-events-people.sparql, scholia/app/templates/event_related-events-timelocation.sparql, scholia/app/templates/event_series.html, scholia/app/templates/event_series_empty.html, scholia/app/templates/event_series_events.sparql, scholia/app/templates/event_series_list.sparql, scholia/app/templates/event_series_map.sparql, scholia/app/templates/event_series_people.sparql, scholia/app/templates/event_series_proceedings-publications.sparql, scholia/app/templates/event_series_recent-publications.sparql, scholia/app/templates/event_series_timeline.sparql, scholia/app/templates/event_series_topics.sparql, scholia/app/templates/event_timeline.sparql, scholia/app/templates/event_topic.sparql, scholia/app/templates/event_upcoming-deadlines.sparql
Implements https://github.com/fnielsen/scholia/issues/1274
=> External SPARQL for event and event_series

scholia/app/templates/catalogue.html, scholia/app/templates/catalogue_images.sparql, scholia/app/templates/catalogue_items.sparql
Patch for https://github.com/fnielsen/scholia/issues/1276
=> External SPARQL for /catalogue/

scholia/app/templates/base.html, scholia/app/templates/organization.html
=> Added ROR identifier for organizations

scholia/app/templates/venue_cito_articles-by-intention.sparql
Fixes https://github.com/fnielsen/scholia/issues/1358
=> Fixed the coloring of the intention type

scholia/app/templates/base.html, scholia/app/templates/cito_empty.html, scholia/app/templates/cito_empty_article-counts.sparql, scholia/app/templates/cito_empty_articles-by-year.sparql, scholia/app/templates/cito_empty_journal-counts.sparql, scholia/app/templates/venue_cito.html, scholia/app/templates/venue_cito_most-reused-articles.sparql
Include:
- now lists the more reused articles in a journal (based on 3 CiTO intention types)
- introduces a CiTO button for journals and works
- some textual guidance
=> Improvements to the CiTO experience

scholia/app/templates/chemical.html, scholia/app/templates/chemical_found-in-taxon.sparql
=> Report the taxons a compound is found in (with source)

scholia/app/static/js/citation.js, scholia/app/templates/work_export.html, scholia/app/views.py
Using citation-js. Result:
Reviewers, what do you think of such a feature?
=> Work aspect "/export" page giving BiBTeX and CITATION.cff. Input wanted.

scholia/scrape/ojs.py
The functions and command-line argument now accept explicit
language specification.
=> Fix #1385: Add explicit language

scholia/scrape/ojs.py
OJS articles with short titles where not match for previous entries
in Wikidata. Now previously entered articles with short articles are found
and trailing slash and fulltext URL are also handled.
=> Fix #1414 OJS match OJS entry

scholia/app/templates/taxon_metabolome.sparql
See https://github.com/fnielsen/scholia/issues/1421
=> Applied optimization suggested by Finn

scholia/app/templates/pathway.html
Implements: https://github.com/fnielsen/scholia/issues/904
=> Added pathway iframe provenance

scholia/app/templates/protein_empty.html, scholia/app/views.py, scholia/query.py
Implements https://github.com/fnielsen/scholia/issues/1083
=> Added redirection for UniProt identifiers

scholia/app/templates/author.html, scholia/app/templates/base.html
- Person annotation for P31 Q5
- added name fields
- added conformsTo info
=> Updates to the Bioschemas annotation

scholia/app/templates/dataset-index.html, scholia/app/templates/dataset.html, scholia/app/templates/dataset_base.html, scholia/app/templates/dataset_citations.sparql, scholia/app/templates/dataset_identifiers.sparql, scholia/app/templates/dataset_list-of-authors.sparql, scholia/app/templates/dataset_topic-scores.sparql, scholia/app/views.py, scholia/query.py
Ammar, Daniel, can I get some initial feedback from you, please? What additional info should be listed for datasets?
Screenshot:
=> Added 'dataset' as aspect

scholia/app/static/js/citation.js
Full config for created `citation.js` bundle:
=> Citation.js 0.5.0 (released version)

scholia/app/templates/404_doi.html, scholia/app/templates/about.html
Implements https://github.com/fnielsen/scholia/issues/1458
=> Adds the 'Submit to QuickStatements' button

CITATION
From https://scholia.toolforge.org/about
=> Add more information to citation

scholia/app/templates/faq.html
* The former two changes correct the sentences which were false
* The latter two changes improve the language used
=> Improve writing in the FAQ

CONTRIBUTING.rst, README.rst, scholia/app/static/scholia.js, scholia/app/templates/base.html, scholia/app/templates/faq.html, scholia/github.py, setup.py
=> Change all old repo URLs to the new URL (#1480)

scholia/app/static/css/scholia.css, scholia/app/templates/about.html, scholia/app/templates/dataset.html, scholia/app/templates/topic.html, scholia/app/templates/work.html
For #1128 
Went through all H3 headings to ensure they were logical.
=> Improve H3 headings (#1128)

scholia/api.py, scholia/app/templates/search.html, scholia/app/views.py
=> [WIP] specialized search fix #26

scholia/app/views.py
fix #129 
add a redirect for arxiv if does not exist
=> arxiv redirect to quickstatement fix #129

scholia/app/views.py
PR #1500 had a too long line for flake8
=> Fix style with too long line

scholia/app/static/scholia.js, scholia/app/templates/work_statements.sparql
=> Add optional units to "supports" statements in work aspect

scholia/app/templates/author.html, scholia/app/templates/country.html
fix #1170
remove commented iframes
=> clean commented iframes fix #1170

scholia/app/static/css/scholia.css, scholia/app/templates/search.html
=> Improve styling of search page

scholia/app/templates/base.html, scholia/app/templates/search.html
=> Add select2 to search results page

scholia/app/templates/search.html
=> Fix next/back being on top of each other

scholia/app/static/css/scholia.css, scholia/app/templates/base.html
=> Always have footer appear on the bottom of the page

scholia/app/static/scholia.js
Missed panels in authors/ etc in the original PR (#1518)
=> Remove unnecessary page controls on Authors and other pages

scholia/app/templates/base.html
As discussed in #1501
This PR will close #1501 
API documentation https://en.wikipedia.org/api/rest_v1/
=> Replace TextExtracts call with REST API

scholia/app/templates/404_doi.html
Suggest in https://github.com/WDscholia/scholia/issues/1508
=> Use a better encodeURI method

scholia/app/templates/author_academic-tree.sparql
=> Highlight academic in academic tree

scholia/app/static/css/scholia.css
First step towards #970
(After is the bottom image)
=> Improvements to header #970

scholia/app/static/scholia.js
=> Round scores and ' per ' columns to 2 dec places

scholia/app/static/scholia.js, scholia/app/templates/location_nearby-organizations.sparql
Depends on #1526 to be merged first. I think once it is merged, this PR will have only one commit
=> Add units to distance metric

scholia/app/templates/index.html
fix #1071 
add a link to covid-19 on home page
=> add covid 19 to home page fix #1071

.gitpod.yml, runserver.py
as per https://flask.palletsprojects.com/en/2.0.x/quickstart/#public-server
=> Gitpod root URL - fixes #1327

scholia/app/templates/base.html
=> Add links to linked to/from to curation pages (#1428)

scholia/app/templates/work_data.sparql
=> Add notice for preprints

scholia/app/static/scholia.js, scholia/app/templates/base.html
Close #1578
Removed the original sparqlToDataTable and renamed it's replacement
Also made the spacing equal between functions in the JS file
=> Remove unused function and rename its replacement

scholia/app/templates/protein.html, scholia/app/templates/protein_participates-in.sparql
The new `/protein/Qxxx` aspect now looks like:
=> Added panel to show in what biological process and protein complexes

scholia/app/templates/software_software-dependencies.sparql
=> add license to dependency graph

scholia/app/static/js/citation.js
Bundle content as specified here: https://github.com/WDscholia/scholia/pull/1454
Fixed the newline QS problem reported here: https://github.com/WDscholia/scholia/issues/1571
=> Update to citation.js 0.5.1 and citation-quickstatements 0.4.1

scholia/app/templates/search.html
=> Improve search results page when no results

.github/workflows/main.yml, scholia/app/templates/clinical-trial-index.html, scholia/app/templates/clinical-trial.html
=> Clinical trial link 1563

.github/workflows/main.yml, scholia/app/templates/base.html
=> Remove duplicate topic 1598

scholia/app/templates/index.html
All the other items in the list are plural
Currently
=> Fix item in home page list

.github/workflows/main.yml, scholia/app/templates/clinical-trial-index_statistics.sparql
=> Add opentrial to statistics 1564 

.github/workflows/main.yml, scholia/app/templates/organization_awards.sparql
=> Add link to authors organization awards 1404

.github/workflows/main.yml, scholia/app/static/scholia.js
This will improve load times and prevent rate limiting.
=> Lazy load iframes

.github/workflows/main.yml, PULL_REQUEST_TEMPLATE.md
=> Add pull request template 943

PULL_REQUEST_TEMPLATE.md
=> copyedits to PULL_REQUEST_TEMPLATE.md

scholia/app/templates/author_coauthor-map.sparql
Fixes a typo discussed [here](https://github.com/WDscholia/scholia/issues/1710#issuecomment-981581029)
=> Layer counter fix in author_coauthor-map.sparql

scholia/app/views.py, scholia/utils.py, tests/test_arxiv.py, tests/test_utils.py
Rebased PR of https://github.com/WDscholia/scholia/pull/1629
=> Encode doi error no ascii characters 1380

.github/ISSUE_TEMPLATE/_bug_report.md, .github/ISSUE_TEMPLATE/_feature_request.md, .github/ISSUE_TEMPLATE/_question.md, .github/ISSUE_TEMPLATE/config.yml, .github/workflows/main.yml
=> Add issue template (issue #942)

scholia/app/templates/work_data.sparql
Warns users if an article cites an retracted article
=> Added warning if the article cites an retracted article

.github/ISSUE_TEMPLATE/add-new-aspect.md, .github/ISSUE_TEMPLATE/add-new-panel.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation-issue.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Added pull request templates for new aspect, new panel and documentation, slightly brushed the existing templates.
=> Update issue templates

scholia/app/static/css/scholia.css, scholia/app/static/scholia.js, scholia/app/templates/base.html
Fix #1599
Add images to item pages inline with table of contents, making sure to resize appropriately. I used this comment to guide my approach, but didn't use any code https://stackoverflow.com/a/34402875
~~The `background-image` property is used as it's the only way to shrink an image to the size of it's neighbour without JS~~
~~For this to be accessible, the appropriate aria-roles should be placed so that it is clear that this is an image. Additionally, the `title=` attribute should be set so …
=> Add image for item inline with table of contents

scholia/app/static/css/scholia.css
Working towards fixing #1031
Add styles to improve printing. I wanted to do a bit more (fix the iframe display, add the link URLs) but couldn't overcome problems in Chrome. There were problems with width in Chrome where the iframes are too narrow and the tables are too wide. 
I also wanted to fix/ease the issue of the WDQS query link appearing in the foreground of the graphs. However, nothing can be done about this as it is in an iframe.
In the end, I've mainly removed the interactive elements (aspect chooser and search) and improved the page margins.
Firefox before and after
Chrome before and after
> Please …
=> Improve print styles

scholia/app/static/css/scholia.css, scholia/app/static/scholia.js, scholia/app/templates/base.html
Working towards closing #903
First commit in this PR refactors the navbar to be more standard bootstrap, so that it will responsive for mobile 
The second commit adds support for mobile 
When the menu is expanded
The third commit adds horizontal scrolling for datatables, which is implemented with JS. The CSS is needed so that the tables display with the full width on desktop
if you make changes to the python code
Please describe the tests that you ran to …
=> Improving mobile support

scholia/app/templates/use-curation.html, scholia/app/templates/use-curation_missing-author-items.sparql
Fixes #1808
Implement use curation page
* Test A
* Test B
=> Fix #1808 implement use curation page

scholia/app/templates/author.html
Fixes #1767
Linking to ... author/Q4765690#citation-statistics now works.
=> fixing the #citation-statistics link in author aspect

scholia/app/templates/software_recent-works.sparql
=> Declare ```target:``` prefix in software_recent-works.sparql

scholia/app/templates/topic-curation_missing-author-items.sparql
also reduced the LIMIT for final results
Fixes #1893
Before:
After:
=> LIMITs in topic-curation_missing-author-items.sparql

scholia/app/templates/work_cito-incoming.sparql
Fixes #1874 
Added an example work per intention.
=> query refined to include example per intention

scholia/app/templates/taxon-curation.html
Fixes #1906
Added specifications for the link prefix of items in the table.
Screenshot for ..taxon/Q202864/curation:
* Test A
* Test B
=> specify link pattern for work items in table

scholia/app/templates/organization-topic_authors.sparql
The match for topic has been broadened.
Fixes #1915
* Test A
* Test B
=> Fix #1915 authors panel in organization-topic

scholia/app/templates/index-statistics_statistics.sparql
=> Added a query to list the number of statements in Wikidata

scholia/query.py
Fixes #1923
Conference article should redirect to work
* Test A
* Test B
There are pydocstyle problems from previous commits
=> Fix #1923 conference article redirect

scholia/app/templates/base.html, scholia/app/templates/software.html, scholia/app/templates/software_authors.sparql, scholia/app/templates/software_data.sparql, scholia/app/templates/software_dependent-software.sparql, scholia/query.py
Fixes #359
Implement/extend software aspect: add to menu, add panels, add aspect guesser.
* Checked various software: SPM, Gensim, Scholia, ...
*
=> Extend software aspect #359

scholia/api.py, scholia/googlescholar.py, scholia/scrape/ojs.py
Fixes #1857
Docstring errors that made generate Sphinx documention faulty.
* cd docs; make singlehtml
=> Fix #1857 Sphinx errors in docstrings

scholia/app/templates/chemical-index_statistics.sparql
Gives a better representation of the experimental data available in Wikidata.
Open https://scholia.toolforge.org/chemical/#statistics
=> Added additional statistics: crystal structures and mass spectra

scholia/query.py
Fixes #1952
Handle EIA reports redirect
* http://127.0.0.1:8100/Q107073812
=> Fix #1952: redirect EIA report

scholia/app/templates/uses.html, scholia/app/templates/uses_authors.sparql, scholia/app/templates/uses_list-of-uses.sparql, scholia/app/templates/uses_list-of-works.sparql, scholia/app/templates/work_data.sparql, scholia/app/views.py
This implementation includes a change in work aspect to show 'use'.
Fixes #1962
New aspect for multiple uses
Viewed generated use via Q112062624
=> Fix #1962: aspect for multiple "use"

scholia/app/templates/uses.html
=> fix the list-of-works heading

scholia/app/templates/venue.html, scholia/app/templates/venue_uses.sparql
Fixes #1967
Use panel on venue aspect
http://127.0.0.1:8100/venue/Q100913796
=> Fix #1967: use panel on venue aspect

scholia/app/templates/venue-use.html, scholia/app/templates/venue-use_works.sparql, scholia/app/templates/venue_uses.sparql, scholia/app/views.py
This includes a link from the venue aspect
Fixes #1969
venue-use aspect that would "list all articles in that journal using that tool" - suggested by @egonw
http://127.0.0.1:8100/venue/Q6294930/use/Q70357595
=> Fix #1969: venue-use aspect.

scholia/app/templates/use_co-used.sparql
This commit includes a fix on counting the number of
works where there is a couse.
Fixes #1974
Zooming on coused. Including a fix on a related count.
For instance, http://127.0.0.1:8100/uses/Q95716584,Q2985668
=> Fix #1974 zoom on coused.

scholia/app/templates/base.html, scholia/query.py
This commit also sorts the items in the aspect chooser code.
Fixes #1982
http://127.0.0.1:8100/Q133895
=> Fix #1982: pathway aspect chooser handling

PULL_REQUEST_TEMPLATE.md
Fixes #1984 
* Test A
* Test B
=> Added some more links to pull request template

scholia/app/templates/topic-use.html, scholia/app/templates/topic-use_works.sparql, scholia/app/templates/topic.html, scholia/app/templates/topic_uses.sparql, scholia/app/views.py
This includes a topic-use aspect as well
Fixes #1988
Use panel on topic aspect
Look at eg http://127.0.0.1:8100/topic/Q19776339#uses
=> Fix #1988 use panel on topic aspect

scholia/app/static/scholia.js, scholia/app/templates/topic_topics.sparql
Fixes #1143 
Count can now be linked to other things in general
I also swapped substr for slice as [substr is deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr)
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide instructions, so we can reproduce. Please also list any relevant details for …
=> Link co-occurring count to the topics/ page

scholia/app/views.py, scholia/query.py
Fixes #1994
Redirect for document
This includes a minor style fix
127.0.0.1:8100/Q112147319
=> Fix #1994 Redirect for document

scholia/app/templates/author-use.html, scholia/app/templates/author-use_works.sparql, scholia/app/templates/author.html, scholia/app/templates/author_use.sparql, scholia/app/views.py
Fixes #1966 
Implement 'use' panel on 'author' aspect. This also includes an author-use aspect
* http://127.0.0.1:8100/author/Q18618629#use
* http://127.0.0.1:8100/author/Q18618629/use/Q2013
=> Feat/author aspect use panel #1966

scholia/query.py
Redirect to work aspect for magazine articles.
Fixes #1936
Redirect to work aspect for magazine articles.
* Checked on [Q47009573](https://www.wikidata.org/wiki/Q47009573)
=> Fix #1936 magazine article redirect

scholia/app/templates/work-curation.html, scholia/app/templates/work-curation_author-resolving.sparql
Fixes #1883 
Add work-curation page
* http://127.0.0.1:8100/work/Q22329404/curation
=> Fix #1883: work curation page

scholia/query.py
New articles are already redirected
Fixes #454
Redirect blogplot and tweet to "work" aspect.
Test with
* https://scholia.toolforge.org/Q24073917
* https://scholia.toolforge.org/Q56119260
=> Fix #454 Redirect blogplot and tweet

scholia/query.py
Fixes #2012
Handle 
Examined the example from the issue
=> Fix #2012 trade magazine redirect

scholia/app/templates/language-index.html, scholia/app/templates/language-index_works-written-in-the-language.sparql, scholia/app/templates/language.html, scholia/app/templates/language_recently-published-works.sparql, scholia/app/templates/work_data.sparql, scholia/app/views.py
Includes a link from the 'work' aspect
Fixes #2014
Implement language aspect
* http://127.0.0.1:8100/language
* http://127.0.0.1:8100/language/Q9035
=> Fix #2014 language aspect

scholia/app/templates/license-index.html, scholia/app/templates/license-index_work-counts.sparql, scholia/app/templates/license.html, scholia/app/templates/license_recently-published-works.sparql, scholia/app/templates/software_data.sparql, scholia/app/views.py
This include the license index page
Fixes #77
License aspect
* Looked on several page, eg., http://127.0.0.1:8100/license/Q13785927
=> Fix #77 implement license aspect

scholia/app/static/scholia.js
Fixes #2022 
* Checked a couple pages, all seems good
=> Show link to WDQS and query before loading finished

scholia/query.py
Fixes #2024
Remove `flask-mwoauth` to avoid a vulnerability in `pyjwt`. The module was not used.
This include an style edit in `query.py` to make it conform and pass the style test.
The current PR does not pass a local tox test!
* x ] There are no remaining debug statements (print, console.log, ...)
=> Fix #2024 Remove flask-mwoauth

requirements.txt, scholia/app/templates/license.html, scholia/app/templates/license_types-of-work.sparql
Fixes #2020
Implement Types of work panel in license aspect
http://127.0.0.1:8100/license/Q13785927
=> Fix #2020 types of work in license aspect

scholia/query.py
"online scholarly workshop" was not handle.
A few more event types were neither handle.
This commit adds a few extra types.
Fixes #2039
Add handling of some event types.
Browsed a few example events.
=> Fix #2039 redirect for online event

scholia/app/templates/author-index.html, scholia/app/templates/base.html
I could not replicate the bug, but this should be the fix
Fixes #2033 
Code was removed in #2026
=> Undo removal of keydown event listener

scholia/app/static/css/scholia.css, scholia/app/templates/about.html, scholia/app/templates/arxiv-to-quickstatements.html, scholia/app/templates/q-to-bibliography-templates.html
Fixes #2044
- Remove definition of custom nav bar — unsure why this was defined in the first place
- Add title to page
- Fix the search button by using the word "Search" instead of an icon which we no longer load from Glyphicons
- As we no longer use glyphicons anywhere in the repository, removed its technical attribution from our about
- Made sure that the tool inputs were consistent by having the buttons connect properly to the input
*If you make changes to …
=> Improve Q to bibliography templates tool

.github/ISSUE_TEMPLATE/add-new-aspect.md, .github/ISSUE_TEMPLATE/add-new-panel.md, .github/ISSUE_TEMPLATE/modify-a-sparql-query.md
Fixes #2087
Please see the changed files for details
I've changed the names so that they all start with nouns rather than verbs (i.e., preferring Bug report over Report bug)
* Test A
* Test B
=> Improve 3 issue templates

scholia/query.py
Fixes #2092 
Also searches for the lowercase version of the twitter username. Twitter usernames can be capitalised but their lowercase versions are unique to one user.
* Checked the two test …
=> Add lowercase twitter username search

scholia/app/static/css/nightmode.css, scholia/app/static/css/scholia.css, scholia/app/templates/base.html
Fixes #2056 
Sorry for the delay, all fixed
* Tested desktop and mobile on light and dark modes
=> Fix hamburger menu

scholia/query.py
Fixes #2095
Recent PR introduced an error on the Twitter lowercase handling. This PR correts.
* 127.0.0.1:8100/twitter/Fnielsen
=> 2095 tox twitter lowercase problem

scholia/query.py
Fixes #2074
Add redirects for doctoral thesis as well as thesis and masters thesis as well as five others.
Before merging it would be worth you also considering if these are valid
* Test A
* …
=> Add eight redirects for works

scholia/app/templates/base.html
Fixes #2055 
As suggested, the fix was the same as for TIF. Perhaps worth enumerating which image filetypes commons supports which aren't supported on the web. 
* /work/Q22810003
* /taxon/Q91703
=> Display SVGs and add case insensitive match

scholia/app/static/scholia.js
I put the code into https://eslint.org/play/ and added the browser+jquery environments and fixed the bugs which are most offending
- Add `var` to declarations. When the `var` is missed out it defines the variable globally
- Remove unnecessary semicolons
- Add comma to list of declarations
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide …
=> Fix ESLint errors

.gitignore, scholia/app/templates/base.html, setup.py
Motivation: I was surprised that the homepage for events wasn't shown, so I wanted to add them. I realized that the links bar was actually controlled by `base.html` and it would be possible to do some logic over `item.claims` to get and display the value, which was already available.
This PR adds a new conditional in the javascript part of `base.html` to introspect over `item.claims` and add a homepage to the links bar, if available. This affects all pages derived from `base.html`. Here's how it looks in two pages:
This PR also enables entrypoints so it's possible to run `scholia run` from the command line after pip installation. There was previous discussion about this in #1471 but for some reason there were issues. I'm hoping that now the project has modernized a bit that this is …
=> Add homepage link to base.html

scholia/app/templates/base.html
Fixes #2114
I've added a generic function for sorting by rank and applied it to selecting the homepage. This function could be applied everywhere we arbitrarily select `[0]`
* Checked the page …
=> Add sortRank function and chose preferred homepage

scholia/app/templates/event.html, scholia/app/templates/event_presentations.sparql
A presentation panel to event aspect
Fixes #2116
A presentation panel to event aspect
* http://127.0.0.1:8100/event/Q50290385#presentations
*
=> Fix #2116 presentations at event

scholia/app/static/scholia.js
Fixes #2115 
Simple fix, used the same code from the default case where there are results
* Tested /venue/Q9672026 from issue and a datatable with results
=> Don't reinitialise data table if no results

scholia/app/templates/author.html
For #1945
This worked with the space, but may as well fix
* Test A
* Test B
=> Fix header ID

scholia/app/templates/software_authors.sparql, scholia/app/templates/software_coused.sparql, scholia/app/templates/software_recent-works.sparql, scholia/app/templates/software_topics.sparql
This changes have been made based on suggestions from #2078.
Fixes #2077
Fix #2077 limits in software aspect. @Daniel-Mietchen had previously done work wrt. the issue. However, there were a few issues with that PR, e.g., double LIMITs.
* Viewed http://127.0.0.1:8100/software/Q1659584
* http://127.0.0.1:8100/software/Q22442795
=> Fix #2077 limits in software aspect

scholia/__main__.py, scholia/arxiv.py, scholia/tex.py, scholia/wikipedia.py
For #1945
https://lgtm.com/rules/1818040193/
```
==================================================== 15 passed in 38.02s ==================================================== …
```
=> Favour `import os` over `from os import` when both are present

scholia/app/static/scholia.js
For #1945
* Add semicolons where they were missed. https://lgtm.com/rules/4860080/
* Define variables https://lgtm.com/rules/3970086/
* Test A
* Test B
=> Add semicolons and define variables

scholia/api.py, scholia/scrape/ojs.py
For #1945
While this is valid code and is clear, it could be confused that the indentation is incorrect as the syntax is rarely used. As such it is better to remove them as it is equivalent https://lgtm.com/rules/5980098/
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide instructions, so we can reproduce. Please also list any relevant details …
=> Remove unnecessary else in loop

scholia/api.py, scholia/scrape/ojs.py
Fixes #2132
PR #2129 introduced flake8 styling errors.
* None
=> Fix #2132 styling errors

scholia/app/templates/event-series.html, scholia/app/templates/event-series_top-topics-through-time.sparql, scholia/app/templates/venue.html, scholia/app/templates/venue_top-topics-through-time.sparql
Area chart with top five topics through time for a venue or an event-series.
Fixes #2090
Area chart with top five topics through time for a venue or an event-series.
* http://127.0.0.1:8100/venue/Q15757263#top-topics-through-time
=> Fix #2090 event series & venue time topic panels

scholia/app/templates/protein.html, scholia/app/templates/protein_cointeracting-proteins.sparql
similar-proteins table that was partially disabled is now erased.
A new panel with some of the functional has been added: cointeracting proteins.
Order of the panels have been changed.
Fixes #2155
See above
* http://127.0.0.1:8100/protein/Q21109355
*
=> Fix #2155 protein aspect did not show panels

scholia/app/templates/event.html, scholia/app/templates/event_use.sparql
Fixes #2157
Use panel on event aspect
Use panel on event aspect
* http://127.0.0.1:8100/event/Q113954954#recent-publications
=> Fix #2157 Use panel on event aspect

scholia/app/static/css/scholia.css
Before and after
_text is invisible in darkmode_
_`<hr>` is invisible in darkmode_
* Test A
* Test B
=> Dark mode fixes

scholia/app/templates/ontology-base.html, scholia/app/templates/ontology-index.html, scholia/app/templates/ontology-index_most-used-ontology.sparql, scholia/app/templates/ontology.html, scholia/app/templates/ontology_recent-works.sparql, scholia/app/views.py, scholia/query.py
Fixes #2165 
> Adds an aspect for ontologies
> Currently not developed a lot, hence WIP. 
Test with the following links:
* http://127.0.0.1:8100/Q55118584 (redirect test)
* http://127.0.0.1:8100/ontology/Q55118584 (aspect about a single ontology)
* http://127.0.0.1:8100/ontology/ (index page)
=> [WIP] Outline of an ontology aspect

scholia/app/templates/base.html, scholia/app/templates/ontology-base.html, scholia/app/templates/ontology-index.html, scholia/app/templates/ontology-index_most-used-ontology.sparql, scholia/app/templates/ontology.html, scholia/app/templates/ontology_recent-works.sparql, scholia/app/views.py, scholia/query.py
Fixes #2165
Further change to PR https://github.com/WDscholia/scholia/pull/2167
* http://127.0.0.1:8100/ontology/
* http://127.0.0.1:8100/ontology/Q135085
=> Egonw aspect/new/ontology

scholia/app/templates/venue-use.html, scholia/app/templates/venue-use_authors.sparql
Fixes #2101
One new SPARQL file for panel on venue-use aspect
* http://127.0.0.1:8100/venue/Q1981225/use/Q23992212
* http://127.0.0.1:8100/venue/Q1251128/use/Q1659584
=> Fix #2101 authors panel on venue-use aspect

.github/workflows/docker-image.yml
=> create docker image and publish it

scholia/app/templates/cito-index_statistics.sparql
=> The venue does not have to be a journal (but can be a preprint server too)

scholia/app/templates/cito-index.html
The previous description did not accurately reflect the query
=> Better description of the query

scholia/app/templates/event.html, scholia/app/templates/event_sponsors.sparql
Change the PR  #2189 of @cthoyt: Column name and explicit URL
* http://127.0.0.1:8100/event/Q111430238#sponsors
=> Cthoyt conference sponsors

scholia/github.py
Change doctest, so if a query to GitHub API fails the doctest reports true.
Fixes #2217
documentation or both
The code does not pass tox, as there is another error.
* `python -m py.test …
=> Fix #2217 GitHub doctest error

scholia/query.py
PR #2231 introduced a style error which made the test fail. It is unclear why there was no warning in the PR.
Fixes #2235
Fix style error
* Test A
* Test B
=> Fix #2235 style error

scholia/app/templates/ontology.html, scholia/app/templates/ontology_data.sparql, scholia/app/templates/ontology_reuse-graph.sparql, scholia/app/templates/ontology_used-by-ontologies.sparql, scholia/app/templates/ontology_used-ontologies.sparql, scholia/query.py
The ontology aspect did not provide a lot of information yet. I'm working with @andrawaag on making this aspect more useful. cc @jmillanacosta
* [ontology/Q55118285](https://scholia.toolforge.org/ontology/Q55118285)
* [ontology/Q1389366](https://scholia.toolforge.org/ontology/Q1389366)
* [ontology/Q116446479](https://scholia.toolforge.org/ontology/Q116446479)
=> More functionality in the ontology aspect

scholia/app/templates/chemical.html
Implements solution for #1913. Further commit for #2245
see #2245
* Test A
* Test B
=> Egonw enable/cdkdepict on toolforge 

scholia/app/templates/cito-index.html
Fixes #2253 cc @dpriskorn 
This patch adds some more information about the CiTO.
* Open the `/cito` page
=> Added more explanation what this page is about

scholia/app/templates/country-topic.html, scholia/app/templates/country-topic_organizations.sparql
Fixes #2276
organization panel on country-topic aspect
Not tested!
* http://127.0.0.1:8100/country/Q35/topic/Q2539
* http://127.0.0.1:8100/country/Q145/topic/Q2539
* http://127.0.0.1:8100/country/Q35/topic/Q903809
=> Fix #2276: organization panel on country-topic

scholia/app/templates/gene.html, scholia/app/templates/gene_identifiers.sparql
Fixes #2280
See https://github.com/WDscholia/scholia/pull/2280
=> Larsgw patch 10

scholia/query.py
=> Small typo in documentation

scholia/app/templates/wikiproject-index.html, scholia/app/templates/wikiproject-index_most-used.sparql, scholia/app/views.py
Fixes #2290
* No applicable testing besides the page working I don't think. The numbers match those from Synia
=> Add WikiProject index page

scholia/app/templates/about.html
Fixes #2199
The Acknowledgment page was very outdated. This patch adds a number of recent presentations showing the growing diversity of functionality (aspects).
Recent grants from @Daniel-Mietchen are still missing.
=> Updated acks

scholia/app/templates/wikiproject.html, scholia/app/templates/wikiproject_co-occurring-wikiprojects.sparql
Daniel raised a couple of things which could be improved on the WikiProject aspect, which I have now fixed
* Ran it locally and made sure the changes are as expected
=> Minor fixes to WikiProject aspect

scholia/query.py
Fixes #2359
Change the doctest (the particular OMIM ID was associated with multiple Q entities)
* python -m pytest --doctest-modules scholia/query.py
* flake8 scholia
* tox -e py310
* 127.0.0.1:8100/omim/181500    # Would usually redirect to schizophrenia
=> Fix #2359 omim doctest failed

scholia/app/views.py
Fixes #2361 
Fix the wrong redirect in the web app redirected with the 'omim' redirect "aspect".
* http://127.0.0.1:8100/omim/181500
=> Fix #2361 wrong OMIM redirect

scholia/app/templates/chemical.html
Implements #2355
Adds a note about the matching Topic aspect page.
* check the two literature sections https://scholia.toolforge.org/chemical/Q209284
=> Added a link to the matching topic page

.github/workflows/main.yml, requirements.txt, tox.ini
See https://security.snyk.io/vuln/SNYK-PYTHON-WERKZEUG-6035177
Fixes #2370
https://www.cve.org/CVERecord?id=CVE-2023-46136
* Ran webserver after `python -m venv scholia-dev; source scholia-dev/bin/activate; pip -r requirement.txt`
=> Fix #2370 Werkzeug security issue

scholia/app/templates/arxiv-to-quickstatements.html, scholia/app/views.py, scholia/arxiv.py, scholia/utils.py
This did not have an issue number! It is coming in from https://github.com/WDscholia/scholia/pull/2337
This incorporates https://github.com/WDscholia/scholia/pull/2337 with further edits to get it to work. It was unclear to me why it did not work.
* Test A
* Test B
=> Improve arxiv tool from carlinmack

scholia/arxiv.py
The language of work property is now always set to English with quickstatements for arxiv identifiers.
Command-line interface erred for wrong arxivs. An error message has been added
Fixes #2373
Set default work language to English for arxiv identifiers. Also fix errors with command-line interace.
* python -m scholia.arxiv get-quickstatements :2310.12450
* Various tests on …
=> Fix #2373 arxiv quickstatements now English

scholia/query.py
Fixes #2383 
Redirect for academy
* 127.0.0.1:8100/Q108805947
=> Fix #2383 redirect of 'academi'

scholia/app/templates/chemical-class-index.html, scholia/app/templates/chemical-element-index.html, scholia/app/templates/chemical-index.html, scholia/app/templates/disease-index.html, scholia/app/templates/gene-index.html, scholia/app/templates/lexeme-index.html, scholia/app/templates/ontology-index.html, scholia/app/templates/pathway-index.html, scholia/app/templates/protein-index.html, scholia/app/templates/software-index.html, scholia/app/templates/taxon-index.html
_Did not open an issue_
This PR adds Wikidata items of the topic illustrated.
There was no direct link to the item corresponding to the topic of the page which seemed suboptimal.
Plurals where also harmonized between pages.
No item was added for "use" as it looked fuzzy to me.
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify …
=> Adding links to topics' items on their relative pages

scholia/app/templates/cito-index_statistics.sparql
=> Fixed small typo

scholia/app/views.py, scholia/doi.py, scholia/utils.py
This includes fixing styling errors in utils.py and views.py as well as the fix for the doctest in doi.py
Fixes #2460
* tox
=> Fix #2460 doctest fails for doi metadata

scholia/app/views.py
If the arxiv could not be matched an error occurred.
Fixes #2459
Fix
* Test A
* Test B
=> Fix #2459 id-to-quickstatement crash fix

scholia/app/templates/taxon_metabolome.sparql
This is a rebased PR. See for all details: https://github.com/WDscholia/scholia/pull/2334
=> Rebased: expanded taxon_metabolome.sparql query to handle direct subclass of (P279) relationship

.github/workflows/main.yml
=> Updated action versions

requirements.txt
Fixes #2488
Update werkzeug package to 3.0.3
* `python runserver.py `
=> Fix #2488 RCE in werkzeug

scholia/app/templates/author-curation.html
Fixes #2449
Add link to author curation page
* For instance, http://127.0.0.1:8100/author/Q89405961/curation
=> Fix #2449 Link to Wikidata Orcid scraper

requirements.txt
Information exposure with requests package
CVE-2023-32681
Fixes #2501 
Fix security issue in requests package by upgrading in `requirements.txt`.
=> Fix #2501 security issue in requests

requirements.txt
CVE-2024-22195
Fixes #2503
CVE-2024-22195 
=> Fix #2503 security issue in Jinja2

scholia/app/templates/base.html
Fixes #880
Add link to Wembedder about page
* http://127.0.0.1:8100/author/Q20895241
* http://127.0.0.1:8100/author/Q18618629
=> Fix #880 Link to Wembedder

requirements.txt
Fixes #2562
Update versions in requirements.txt as suggested by Snyk.
=> Fix #2562 security issues in zipp and urllib3

scholia/qs.py, scholia/scrape/openreview.py
Fixes #2567
Scraping of OpenReview
* python -m scholia.scrape.openreview paper-url-to-quickstatements https://openreview.net/forum?id=0g0X4H8yN4I
* python -m scholia.scrape.openreview paper-url-to-quickstatements https://openreview.net/forum?id=oX9lqjkzXq
=> 2567 scrape from openreview

scholia/app/templates/topics_authors.sparql
Fixes #2583
Changed SPARQL for better author scoring in multiple topics aspect
* http://127.0.0.1:8100/topics/Q52,Q2013
=> Fix #2583 Better author score for multiple topics

scholia/app/templates/base.html, scholia/app/templates/index.html
Fixes #2549
Banner and some adjustments on the container levels and code indentation.
* http://127.0.0.1:8100/author/Q18618629
=> Fix #2549. Add banner about graph split

.readthedocs.yml
Fixes #2575
Update Ubuntu and Python versions
* Not tested!
=> Fix #2575 Update Read the Docs config to Python 3.11 and Ubuntu 24.04

.readthedocs.yml, docs/requirements.txt, tox.ini
Fixes #2575 
There were problems with dependencies. conf/requirements.txt have been edited and an environment in tox have been created.
* tox -e docs
* https://app.readthedocs.org/projects/scholia/builds/27756362/
=> 2575 update readthedocs workflow

scholia/app/templates/base.html
This change also disable note about graph split problem
Fixes #2548
Scholia Survey link.
* Test A
* Test B
=> Fix #2548: Add link to Scholia Survey on all pages

CONTRIBUTING.rst, README.rst, scholia/app/static/scholia.js
Fixes part of #1762  
We have a number of mentions of Scholia's master branch [throughout the code base](https://github.com/search?q=repo%3AWDscholia%2Fscholia%20master&type=code).
Some of the URLs in the codebase refer to master branches of other repos, which we should perhaps check separately. 
In principle, this is a breaking change, but on GitHub specifically, it should not cause any problems, as per https://github.com/github/renaming?tab=readme-ov-file .
* Test A
* Test B
=> Daniel mietchen master main 1762

scholia/app/templates/base.html, scholia/app/views.py
Fixes #2600
Edit robots.txt and noindex in meta tag
* http://127.0.0.1:8100/robots.txt
=> 2600 in robotstxt allow some pages to be indexed main about index

scholia/app/static/scholia.js, scholia/app/templates/base.html, scholia/app/views.py, scholia/config.py, scholia/googlescholar.py
Fixes #2598 
Test with doctest for Google Scholar sometimes failed on GitHub. Here a try-except is wrapped around the test.
* tox
=> 2598 tox fails in googlescholarpy

scholia/app/templates/dataset-index.html
Fixes #2622
It replaces an old dataset and adds two further examples. 
* https://scholia.toolforge.org/dataset/
=> Three new datasets

scholia/app/static/scholia.js
This implements the idea that some SPARQL queries need to run on a different endpoint than the global configuration (e.g. in `scholia.ini`).
This patch uses JavaScript to parse the SPARQL file content. It looks for comments with a certain structure (in the `extractConfig()` methods, which creates a JavaScript object), as given below. When the `sparqlToDataTable2()` method is called, the method extracts the config information, and if found, overwrite the global configuration values.
Supported are:
* `#sparql_endpoint=`, for the SPARQL endpoint
* `#sparql_endpoint_name=`, for the name of the SPARQL endpoint
* `#sparql_editurl=`, for the URL pattern to open the SPARQL in the editor of the SPARQL endpoint
* `#sparql_embedurl=`, for the URL pattern to SPARQL query results in embedable form …
=> Adds support for SPARQL-level configuration

scholia/query.py
Fixes #2660
Redirect of research proposals to work
*  https://scholia.toolforge.org/Q134545539
=> Fix #2660 Redirect of research proposals to work

scholia/app/templates/work_cited-works.sparql, scholia/query.py
Fixes #2673 (an error introduced)
Fixes a programming error introduced for the fix of #2673. The fundamental problem is still not resolved.
=> 2673 internal server error on redirect

scholia/api.py, scholia/app/views.py
Redirect in the Scholia web app used SPARQL to get 'instance of' information for choosing the appropriate aspect. There has recently been Internal Server Error associated with this use it seems.
Now the download of the 'instance of' happens via the API. Whether this approach helps on the fundamental problem is not clear. It is difficult to test as the problem only occures on the Toolforge version of Scholia, - not locally.
The long 'if'-sentence for aspect guessing is now copied to 'views.py' which seems to be a more appropriate place.
The new approach is not so general as the SPARQL-based approach as some selection was based on a '+' property search.
This commit also include a fix for the CLI on search that did not work.
Fixes #2673
See above
> Please list anything which has been left …
=> Fix #2673 Use API instead of SPARQL for redirect

versioneer.py
Fixes #2604
Versioneer issue fix for SafeConfigParser and whitespace issue
* Test A
* Test B
=> Async arijit fix/versioneer python3
