WDscholia/scholia

- scholia/app/templates/chemical_empty.html
Small update for the chemical 'front page' (aka "empty") to show an example of the InChIKey support for looking up chemicals.
> InChIKey example in emtpy page

- scholia/app/templates/chemical.html
Chemical can have multiple, for example, boiling points, under different conditions. The latter are modeled as qualifiers in Wikidata and now added. Units are still missing, and I may do that later, but people can look that up, but it clarifies enough why there are multiple values for 'boiling point'.
> Added physchem qualifiers (without unit)

- scholia/app/templates/chemical.html
Patch that adds two sections. The queries are slightly different from that of topic, as I specifically want to include works use as 'reference' of physchem properties.
Also fixed a duplicate < h2 > ID.
(I also note that that "data" and "field study" (e.g. for acetic acid) are not recognized as "works" and redirect to topic...)
> Added publications about the chemical

- scholia/app/templates/authors.html
The Wikidata Query Service UI, including the embed version, now retries queries with POST if the GET request fails because they’re too long (this was implemented in [Ic3ea53c50e][1]), so there is no hard limit on the number of authors. (The query sometimes fails for other reasons, but that can also happen with less than five authors.)
[1]: https://gerrit.wikimedia.org/r/#/c/355131/
> Remove note from co-author graph

- scholia/app/templates/base.html
Currently, I think there is no direct link from any Scholia page to the Wikipedia article, even though it *is* referenced. I can't test right now, but it seems like a trivial change.
> Add link to Wikipedia article

- scholia/query.py
Apparently, wdt:P31 only gets a subset of classes when priorities are used. For example,
acetic acid has "carboxylic acid" as higher priority class, so that at an RDF level
only that one is given. We have, however, access to all classes via the statements.
> Fixed getting the classes of things (closes #275)

- scholia/app/templates/event_series.html
At https://www.wikidata.org/wiki/Wikidata:WikiProject_Events the proposed property is P31 so this should be supported. I have not tried whether this may lead to timeouts.
> Also support P31 to select events of a series

- scholia/app/templates/award.html
For instance <https://tools.wmflabs.org/scholia/award/Q42092479> (the scholarship is awared for time spans such as 2018/2019).
> Add year of award if only given by start time (P580)

- CONTRIBUTING.rst
There *is* an [`and`](https://packages.debian.org/stable/and) package on Debian, but this looks like a typo.
> Remove 'and' package from Debian install command

- scholia/app/templates/chemical.html
Finn, I basically just introduce SAMPLE() to pick a random formatter URL so that each identifier only shows up once (e.g. "canonical SMILES" has two).
> Use only one formatter URL, so ensure each identifier only shows up one

- CONTRIBUTING.rst
The link is invalid because a comma is used instead of a dot, with this change the link should be directly accessible again.
We are going to use Scholia as a part of a software project at my university, there might be future contributions to Scholia if we have anything meaningful.
> fix Wikidata Query Service link

- scholia/app/templates/author.html
- scholia/app/templates/faq.html
SourceMD is currently disabled so links from Scholia does not work.
> Fix #795: Remove link to SourceMd

- scholia/app/templates/event.html
For "Related based on time and location" panel in event aspect results
would not show up if the location did not have a geo-coordinate, but
could be located via the headquarter geo-coordinate.
> Fix #793: related events in event aspect

- scholia/app/templates/pathway_empty.html
- scholia/app/views.py
- scholia/query.py
Adds redirecting for WikiPathways identifiers and a more helpful 'empty' page (early version):
This supports the work of WikiPathways, which increasingly links to Wikidata, via Scholia.
> Updated pathway support

- scholia/app/templates/pathway.html
- Introduces two new sections: An interactive pathway viewer iframe and a link to organism
- Utilizes a new generic sparql query that is extensible for future uses
- Fails gracefully by hiding sections if data is not available
- Adds `const` per convention
Please let us know if we can improve upon this PR in any way. We are eager to contribute to scholia for pathway views.
> Additional properties and interactive views for pathways

- scholia/query.py
chemical_symbol_to_qs and associated command-line argument
did not work.
> Fix #843: Name error for chemical_symbol

- scholia/tex.py
1. One thing I found a bit confusing is that even with the accent conversion working (i.e., the BibTeX output contains just `{\. s}`, pdfLaTeX on Overleaf still complains about an unknown Unicode character, *with* `\usepackage[utf8]{inputenc}`.
2. I'm not really familiar with Unicode strings in Python 2.7 yet, so there may be some problems there.
3. For other symbols, there's [a great, big list](https://www.rpi.edu/dept/arc/training/latex/LaTeX_symbols.pdf) and I don't really know if we want to include all of that.
See #61
> Support UTF8 in TeX output

- scholia/app/templates/event.html
The first table in the event aspect showed the word "pubs" as
a short form of publications. "Works" might be more understandable.
> Fix #818 renaming "Pubs" to "Works"

- scholia/app/templates/award.html
Add description column to the co-award panel in the award aspect
as a partial implementation of #861.
This commit also changes the HTML element identifiers, changing
a whitespace to a dansh #857.
> Add description to co-award panel #861

- scholia/app/templates/pathway.html
- Makes use of extensible query for simple values to minimize number of queries
- Uses `div id` pattern
- Display of description matches that of other scholia templates that pull from Wikipedia (thus the `<br />`
- We are responsible for maintaining the wikidata content feeding this new description field and will keep them in sync if future changes are made
Example item with description data: https://tools.wmflabs.org/scholia/pathway/Q66104607
> adds description to pathway template

- scholia/app/static/scholia.js
If SPARQL returned empty results a variable that may be used in HTML should be escape with the escapeHTML function. escapeHTML now works with undefined input.
> Fix #963: Now escapes undefined

- requirements.txt
Tox is not necessary for running the program. Tox is only neceesary during
testing.
> Fix #968: Remove tox from requirements.txt

- scholia/app/templates/award_missing.html
Fixes #982 and also addresses #972
> adding H1-level page header to missing page for awards

- scholia/app/templates/organization_missing.html
Fixes #598 by 
- adding a new panel that highlights author name strings matching those of the organization's affiliates
- splitting the existing table for co-authors into strings with and without initials
> Enriching the missing page for organization aspect

- scholia/app/templates/author_empty.html
Adds a link from
https://tools.wmflabs.org/scholia/author/
to
https://tools.wmflabs.org/scholia/authors/Q71522746,Q28468766,Q28468763,Q24532211,Q24244119,Q24727868,Q78549817
> Adding an example for comparing 7 authors

- scholia/app/templates/chemical.html
This solves the problem that the SMILES and InChI were messing up the layout of the identifier table (with the value column way too wide).
> Patch to fix #870 and add the chemical structure info as a separate table

- scholia/app/templates/index.html
- scholia/app/templates/organization.html
- scholia/app/templates/organization_empty.html
- scholia/app/templates/organization_topic.html
- scholia/app/views.py
This adds a topic subaspect for an organization profile and links to it from 
- an organization's profile
- the organization aspect's landing page (for some examples)
- the Scholia landing page (for one example).
Fixes #437 .
> Adding a subaspect for organization and topic

- scholia/app/templates/author_missing.html
Modified the query for "Author name strings to be resolved" on the /missing page for authors, such that it includes strings that occur in "stated as" qualifiers for P50 (author) statements involving this entity on publicaiton items.
> Closing #608

- scholia/arxiv.py
This has not been tested on a multithreaded uwsgi system.
The fallback on "from xml import etree" should work in theory.
> Attempt to fix lxml import error #1050

- scholia/app/templates/base.html
- scholia/app/templates/event.html
- scholia/app/templates/event_series.html
- to pages that already showed some info
- and details are now shown for events and event series too
- Twitter account 
- hashtag, which points to the wmflabs hashtags-hub service
> adds Twitter accounts and the hashtag (implements #1045)

- scholia/app/templates/author_missing.html
better text about author disambiguation on the missing page for authors
> better text about author disambiguation on the missing page for authors

- scholia/app/templates/chemical_empty.html
The two "article" queries take some 13 and 16 seconds each. Interesting info, but not for being dynamically generated.
> Removed the counting of chemical<>articles links which takes too long

- scholia/app/templates/chemical_empty.html
- scholia/app/templates/chemicals_missing.html
- scholia/app/views.py
- with column on the `/chemical/` frontpage
- adds a few more example chemical structures 
I expect more patches later for more physchem properties from @lahire.
> Adds a chemistry/missing page for curation

- scholia/app/templates/venue.html
Updated patch (replaces #876) to add retracted works to a journal (venue) instead of publisher
> added retracted works to venue (journals)

- scholia/app/templates/clinical_trial.html
Add link to OpenTrials via its identifier implementing #621
The icon that indicates an external link is also changed to a northeast arrow.
> Add link to OpenTrials

- scholia/arxiv.py
- scholia/tex.py
- tests/test_arxiv.py
The datetime was not extracted correctly.
The URL for scraping has been changed to export.arxiv.org.
> Fix problem with arxiv scraping #1059

- scholia/app/templates/gene_empty.html
- scholia/app/templates/taxon_empty.html
- scholia/app/views.py
- scholia/query.py
Adds two CLI methods:
* `python -m scholia.query ncbitaxon-to-q 694009`
* `python -m scholia.query ncbigene-to-q 5604`
Second, it upgrades the empty `gene` and `taxon` aspects with the column layout, featuring the two redirects, here for taxon:
**Important**: unlike with most other redirects, I decided here to use simply `ncbi`, but because ncbi has many identifiers, I use the aspect as context.
> Added NCBI gene and taxon IDs to the UI

- README.rst
- scholia/__main__.py
- scholia/app/templates/arxiv_to_quickstatements.html
- scholia/app/templates/author.html
- scholia/app/templates/base.html
- scholia/app/templates/faq.html
- scholia/app/templates/lexeme.html
- scholia/app/templates/pathway.html
- scholia/arxiv.py
- scholia/scrape/nips.py
Changed links to other Toolforge tools to use toolforge.org and changed Tool Labs to Toolforge in the README file
> Update Toolforge URL

- scholia/app/templates/taxon.html
It currently only uses `found in taxon` but P1582 has been proposed for use for natural products.
> Also use P1582 to link metabolites (natural products) to taxons

- scholia/app/templates/work.html
Let author table in work aspect show the short author name.
A link is created to the author-disambiguator.
Description is also added.
> Implement short author name #549

- scholia/app/templates/work.html
Fix a URL formatting error introduced in https://github.com/fnielsen/scholia/commit/58c8575790be55d257b0b2306a93fc5fd58128aa when fixing https://github.com/fnielsen/scholia/issues/1177 .
> quick fix for the author disambiguator link

- scholia/app/templates/author.html
- scholia/app/templates/authors.html
- scholia/app/templates/event_series.html
- scholia/app/templates/venue.html
Som columns that displayed multiple authors and topics did not
link to the authors or topics aspects. Now some of these cases
have been linked.
This relates to #1214 and #1215
> Add links from multiple authors and topics

- scholia/rss.py
If Wikidata entities had no date then the rss feed would
raise an error. Now entities with no date are skipped from
the RSS feed
> Fix #1224 RSS feed errs with no date

- scholia/app/templates/work.html
- scholia/app/views.py
- scholia/query.py
The Wikipedia mention table now also search on DOI for Wikipedia citations.
This require a server-side query to get the DOI to get a list of DOIs.
The extra query seems not to delay the generation of the table too much.
> Implement search on DOI #1234

- scholia/app/templates/event.html
Authors and topics in the proceedings publication panel in the event asepct are
now linked to the authors and topics aspect.
> Fix #1238 link authors and topics

- scholia/app/templates/base.html
At this moment it hardcodes the domain name, but that will be solved after https://github.com/fnielsen/scholia/pull/1037 is merged in.
> Added a canonical URL link (implements #1151)

- scholia/app/templates/work.html
Academic age is added to the list of authors on the work
aspect page. It is computed from the first publication date
of the author.
> Add academic age to author list #1261

- scholia/app/templates/work.html
Observation ("Alex R Pico" is duplicated):
> Removed some row duplication.

- scholia/app/templates/work.html
Previous SPARQL query only query all works to compute academic age.
Now only scholarly articles are queries. Perhaps other forms of works
should also be added to the query, e.g., academic book, though these
might be difficult to identify.
> Fix #1331: academic age compute on academic works

- scholia/app/templates/organization_employees-and-affiliated.sparql
The employee and affiliated list on the organization aspect counted
authorship. This was shewed because of authorships of biological pathways.
Now the authorships of biological pathways are excluded from the counts.
This relates to PR #1318 that used the non-external SPARQL queries
> Drop pathways from count on organization

- scholia/api.py
Bib file generation from aux did not work in Python3 due to use of itervalues.
It is now changed.
> Fix #1345 writing bib from aux

- scholia/app/views.py
- scholia/query.py
This PR adds a route `/biorxiv/<biorxiv_id>` to the application similar to its function for arXiv. Since they work almost identically besides the Wikidata property used, some of the code was abstracted into helper functions and reused for both.
> Add bioRxiv route

- scholia/app/templates/work_empty.html
- scholia/app/views.py
- scholia/query.py
Similarly to #1323, this PR adds support for using the newly minted ChemRxiv property (P9262) as a lookup.
Example:  ChemRxiv identifier [13607438](https://chemrxiv.org/articles/preprint/Enantioselective_Conjugate_Addition_of_Catalytically_Generated_Zinc_Homoenolate/13607438) points to [Q104931192](https://www.wikidata.org/wiki/Q104931192). There aren't a ton of identifiers pre-populated, but I have written a script with the Wikidata Integrator that can add the rest.
> Add initial ChemRxiv support

- scholia/app/templates/arxiv_to_quickstatements.html
- scholia/app/views.py
The old Quickstatement did no longer work and this commit change
so the link goes to the new Quickstatement tool (V2).
The link is also changed to a button.
> Fix #1258 new redirect for arxiv-to-quickstatements

- scholia/tex.py
When writing a bib-entry, the key must not be escaped, otherwise
bibtex will not find the key given in the tex file in the bib file.
One example where this breaks without this change is the DOI
10.1007/11925941_2 (due to the underscore). Underscores are special
characters in LaTeX, but not in Bibtex keys, and are allowed in
DOIs.
> scholia/tex.py: Do not escape bibtex key

- scholia/app/templates/project.html
A change in the id for the H1 tag meant that the title of the project no
longer was showing. This fix change the name back.
> Fix #1349 so project header is showing

- .github/workflows/main.yml
- requirements.txt
- scholia/tex.py
- tox.ini
Vulnerability for lxml, see:
https://pypi.org/project/lxml/
Remediation: Upgrade lxml to version 4.6.3 or higher.
> Fix #1304 security issue for lxml

- scholia/scrape/ojs.py
OJS author was in some instances not extracting the author name if
there was only one author.
> Fix #1390 scraping OJS author

- scholia/scrape/ojs.py
Now checks if metadata field is empty before returning value.
Now includes a check on DC.Title.Alternative if DC.Title and citation_title
are empty.
Switch language detection to 'DC.Language', 'citation_language', although this
apparently does not solve every all cases.
> Fix #1370 OJS missing title

- scholia/app/templates/base.html
It works by adding a `<meta>` element, which is the "semantic" data needed by the Unpaywall extension. See https://support.unpaywall.org/support/solutions/articles/44002172370-how-do-i-make-the-unpaywall-extension-work-on-my-site-
In action:
> Added a <meta> element for Unpaywall support

- scholia/tex.py
- tox.ini
A doctest contained a wrong escaping discovered in the py37 and
this error is also fixed
> Fix #1405: Add py37 to tox testing

- scholia/app/views.py
When multiple authors and topics aspects receives only a single
identifier the request is now redirect to the single aspect,
author and topic respectively.
> Fix #1285: redirect to single aspect

- scholia/app/templates/event_series_events.sparql
Proceedings that was not associated with an event did not show up.
Now the query has been expanded to capture the proceedings based
on their association with the proceedings series.
> Fix #1403: Add proceedings for event series

- scholia/app/templates/event_recent-publications.sparql
The recent publications for people associated with an event now
also takes the publications from the editor of the proceedings.
> Fix #1447 add editor recent publications

- scholia/app/static/scholia.js
- scholia/app/templates/base.html
- scholia/app/templates/work.html
- scholia/app/templates/work_data.sparql
It uses the same three different ways Wikidata currently can mark an article as retracted (two in one UNION clause). The output looks like:
> Added retraction info

- scholia/app/templates/venue_recently-published-works.sparql
When publications had multiple publication dates an author would
appear multiple times in the "recently published works" panel in the
venue aspect. With a distinct an author now only is listed a single time.
This might cause confusion if there are multiple different authors with the
same name. Alternatively the SPARQL should be further refined.
> Fix #1459: venue panel distinct authors

- scholia/app/templates/work_cited-works.sparql
Count for cited works in work aspect counted double (or more)
if the work had multiple publication dates
> Fix #1473: missing distinct in citation

- scholia/app/templates/dataset.html
The deleted text is a duplicate of the lines directly above. You can see this duplication at the bottom of a dataset page https://scholia.toolforge.org/dataset/Q4203254
> Remove duplicate aspect

- scholia/app/static/scholia.js
Controls that cannot be used are distracting
> Hide paging controls if there is only one page

- scholia/app/static/scholia.js
- scholia/app/templates/index-statistics.html
Close #1515 
Also added the search box back to the statistics page (bug)
> Right align and comma separate all "Count" columns

- scholia/app/templates/base.html
This PR replaces the JS QID exists check with a Jinja template check instead.
This means that the JS will not appear on pages it isn't needed, reducing page size.
For example, the /author/ page goes from 27kb to 12kb.
Pages which do need the JS are not affected
> Reduce page size by only loading necessary JS

- scholia/app/views.py
A recent change introduced a Python3 syntax. This change
change it to a python2/3 compatible syntax.
> Fix #1528: Python2 incompatible syntax

- scholia/app/static/scholia.js
fix #301 
add verification for empty results hiding empty iframe
add a link to Wikidata for change query
change messages for empty results of Datatables
> fix #301 query yield no results

- scholia/app/templates/base.html
'Taxon' button is missing:
And added by this PR:
@carlinmack, when you think the patch is okay, add your reviewer decision, assign to Finn, and add the label 'ready for merge'.
> Added detection of taxons for creating buttons

- requirements.txt
- scholia/arxiv.py
- scholia/arxiv_.py
Close #43 and close #1059
This is an exact replica of the previous version using the API instead
---
Message about the first commit:
> I looked into the API and they only serve [Atom](https://en.wikipedia.org/wiki/Atom_(Web_standard)) not JSON or anything familiar. They recommend using [feedparser](https://pypi.org/project/feedparser/). As we would be importing an external module any way, I looked into it and found the [arxiv](https://pypi.org/project/arxiv/) module. This makes things really easy and externalises the handling of the API to another project, great!
> Unfortunately as the name clashes with the file, and Python does not like importing things with the same name we either have to:
> [ ] Find a workaround for the Python import system which is robust (I looked into a lot of …
> Use arXiv API

- tests/test_arxiv.py
Testing for the arxiv module depends on the data
on Wikidata. It has changed so the test must change.
A test for the publication date has been deleted as
the publication date was already tested with other lines
of code.
> Fix #1642 correct test in arxiv

- scholia/app/templates/work_data.sparql
Implements https://github.com/WDscholia/scholia/issues/1638
New table looks like:
> Added the language of a work

- scholia/app/templates/base.html
Previously, the sublist would only be added if there was a following H2. This went unnoticed as this is almost always the case. The affected aspects are event_series.html, event.html, publisher.html, topic.html and works.hml
> Fix table of contents bug

- setup.py
When building the Scholia package the data files, such as html, js, and sparql,
were not included in the distribution package. That meant they were not
installed when installing with pip. Now they are explicitly mentioned with the
package_data field in the call to setup in setup.py.
> Fix #1633 set package_data in setup.py

- README.rst
- scholia/__main__.py
- setup.cfg
This PR does the following to make it easier to develop Scholia locally:
1. Adds documentation in the README on how to install Scholia locally
2. Adds an entrypoint in the setup.py file so you can run `scholia` from the shell instead of `python -m scholia`
3. Adds a `run` command to the CLI that mimics `runserver.py`
> Simplify running Scholia locally

- scholia/app/templates/base.html
- scholia/app/views.py
- scholia/query.py
@fnielsen, this is now a finished patch, but if you have additional ideas, plz let me know (if not, please do merge in).
The new design solve the problem of the `robots.txt` blocking calls and limiting the SEO indexing of Scholia pages:
- a Scholia proxy is defined with the URL pattern `/$qid/bioschemas` which returns JSON
- the existing `base.html` uses this new call instead of a call to wikidata.org (with the `robots.txt` problem)
The extra call is only made when the aspect template has an `id=bioschemas` holder.
Possibly future optimization:
> Add Bioschemas by proxying Wikidata content (making Google bots happy)

- scholia/app/__init__.py
- scholia/text.py
text-to-topics did not work for the tox testing because of time outs, meaning that
local testing did not work.
This commit changes the text-to-topics, so only a subset of
articles and topics are downloaded and instead of saving the object as a
pickle the data is saved in a JSON file.
> Fix #1645: change text-to-topics to JSON-based

- .github/workflows/main.yml
- scholia/app/static/scholia.js
fix #1646 
add message when query fail also add a link to Wikidata to edit the query
> Add message when query fail 1646

- scholia/app/templates/country_topic.html
"Authors of the country who published on the topics" panel in country-topic
aspect had wrong links. This is now fix with linkPrefixes optional
arguments.
* Test A
* Test B
> Fix #1547 wrong links in country-topic

- scholia/arxiv.py
If a newline was present in an arxiv title, then quickstatement would not accept
it. This removes the newline from the scraped content.
Fixes #1672
Fix newline in arXiv title
* Test A
* Test B
> Fix #1672 newline in arxiv title

- scholia/app/templates/topic-curation_missing-author-items.sparql
This adds the author score (using same scoring logic as in [author-scores.sparql](https://github.com/WDscholia/scholia/blob/0f891e9c6be2edad3de0e5b2ce32c4b5b6558afa/scholia/app/templates/topic_author-scores.sparql)) to the missing-author-items query on the topic curation page.
Prior to this, the only way to sort the list of missing authors was by their work count.
After you disambiguate the top authors, you're usually left with a long tail of authors who only have one or two works on the subject. Adding a "score" column to the table to makes it easier to prioritise disambiguation efforts.
* This is **not** a breaking change
* It only changes a single SPARQL query
* It should slightly increase the query time but the change is so small that it's hard to measure
* I don't believe any docs …
> Add author score to the missing-author-items query

- scholia/app/views.py
We had an old robots.txt for the wmflabs with subdirectory.
As the Toolforge Scholia domain is changed to scholia.toolforge.org
then the robots.txt was no longer having a correct path and should
thus be ineffective.
Search engines index dynamic content on Scholia pages differently:
Bing and Quant seems to index the content, but Duckduckgo and Google do
apparently not, see #1709.
With this change, not only is the path change, but bots are now allows.
If this results in too much load on the Toolforge infrastruture then it
should be changed to a 'Disallow: /'.
Note that the 'robots' HTML meta tag on each Scholia page has a nofollow
to avoid crawling.
Fixes #1709 (attempt to partially fix - perhaps not likely to do it)
Fixes an old robots.txt. Now allows bots.
> Please list anything which has …
> Change robots.txt #1709

- scholia/app/static/css/scholia.css
- scholia/app/static/scholia.js
Close #1574. Loaders added for all DataTables
Animation looks like this https://codepen.io/carlinmack/pen/ZEKmoYr
Before
After
----
Before
After
> Add loading animations for tables

- scholia/utils.py
- tox.ini
The #1722 pull request introduced a couple of minor styling errors as well
as an incompatibility with Python 2 and since this was tested via the tox.ini
file, a text with tox would err.
This PR fixes the two styling errors and also more importantly removes the
test with Python 2.7, so that Python 2.x is no longer supported. The default
Python installation on older Linux system, e.g., Ubuntu 18.04 LTS would then
not work. python3 in such systems which uses 3.6 should now still work,
thus Scholia should be started with python3 runserver.py on such old systems.
> Please list …
> Fix #1736: Tox error and style error in #1722

- requirements.txt
Fixes #1746 .
[The underlying ticket](https://github.com/advisories/GHSA-55x5-fj6c-h6m8) states
> "The issue has been resolved in lxml 4.6.5."
So upgrading to ```lxml>=4.6.5```
> updating lxml to lxml>=4.6.5

- scholia/app/templates/base.html
Fixes  #1587
Add 'complex' to topic menu: It was missing.
1. `python3 runserver.py`
2. Open webbrowser on http://127.0.0.1:8100/
3. See that 'complex' is under 'Topic' menu
> Fix #1587: Add 'complex' to menu

- scholia/app/templates/use-index.html
The item in "use" column the "most used" panel in the "use" aspect
would typically redirect to a topic, rather than a use aspect.
This change explicitly link to the use aspect for that column.
The PR #1628 also work on this issue.
Fixes #1192
* Test …
> Fix #1192: use column link in use aspect

- scholia/app/templates/author_curation.html
- scholia/app/templates/award_curation.html
- scholia/app/templates/organization_curation.html
- scholia/app/templates/q_curation.html
- scholia/app/templates/topic_curation.html
- scholia/app/templates/venue_curation.html
- scholia/app/views.py
Close #281 . Working towards closing #374
Based on what I wrote in #1556, I've improved the curation pages and added pages for all aspects
Before and after where there is an existing curation page for aspect:
Before and after where there is __not__ an existing curation page for aspect:
> Add curation pages for all aspects

- scholia/app/templates/organization-curation.html
Fixes #1776
Fixed the block for curation panels
> putting panels back into organization curation pages

- scholia/app/templates/q_curation.html
Fixes #1775 
A simple link fix. I went for the ```/entity/``` option.
> corrected the link from curation page to Wikidata item

- scholia/app/templates/q_curation.html
Fixes #1770
Added the missing equal sign.
> added missing equal sign to URL parameter in WhatLinksHere link from q_curation.html

- scholia/app/templates/pathway.html
Pathway aspect did not show. The name of the sparql
file in the HTML template was wrong.
Fixes #1789
Fix the problem that the pathway aspect did not show and generated an error.
* Test A
* Test B
> Fix #1789 pathway aspect did not show

- scholia/app/static/css/scholia.css
Syntax error has been fixed and lines have been reordered.
Fixes  #1794
Style errors in webpages was due to syntax error in Scholia's CSS file.
* Test A
* Test B
> Fix #1794: wrong syntax in CSS

- scholia/app/static/scholia.js
The horizontal scrollbar was shown in the table even
though the full table width was displayed.
Fixes #1805
The horizontal scrollbar was shown in the table even though the full table width was displayed. The scrollbar is disabled now.
* Test A
* Test B
> Fix #1805 disable horizontal scrollbar

- scholia/app/templates/use_authors-of-works-using-the-resource.sparql
Fixes #1813 .
Adds a ```LIMIT``` to the ```authors-of-works-using-the-resource``` query on the ```use``` aspect.
> adding a LIMIT

- scholia/app/templates/base.html
2nd half of closing #1322 
Close #1122 
This PR adds a link to the curation page for all Q number pages. 
This PR relies on #1552 as the curation aspect chooser is filtered based upon whether there is a useful curation page for that aspect. On this curation page, the aspect chooser is filtered of the aspects which don't have curation page templates:
----
I'm happy with this PR now, text below preserved for reference
---
This needs some iteration/discussion before it's ready, due to design choices etc.
The position was chosen as users are accustomed to finding edit controls in the top right of the page. 
In terms of the text:
* "Edit" would have to direct the user to Wikidata, which would be odd
* "Curate" does make sense if you have the right mental model, but would be initially confusing …
> Add links to curation pages

- tox.ini
This adds py38 and py39 options to the configuration file of tox.
It does not add them to automatic testing if `tox` is run without
environment parameter.
Fixes #1838
We would like to be able to test with tox on the py38 and py39. This adds the options to `tox.ini`.
* Test A
* Test B
> Fix #1838 tox testing on py38 and py39

- .gitignore
Add .project and .pydevproject to the .gitignore file.
Fixes #1830
For development add .project and .pydevproject to gitignore
> Fix #1830 Eclipse to .gitignore

- scholia/app/templates/venue.html
Fixes #1861 
Added a link to the IRI for CiTO.
Before:
After:
> add link to CiTO from CiTO section on venue aspect

- scholia/app/templates/pathway_citing-articles.sparql
Fixes #1868 
Added a declaration of the ```target:``` prefix.
Works as expected now.
> add PREFIX declaration to scholia/app/templates/pathway_citing-articles.sparql

- scholia/app/templates/topic.html
Fixes #1880
Added a line break between [Map of organizations associated with works about the topic](https://scholia.toolforge.org/topic/Q110983345#organization-map) and [Citation graph of works about the topic, aggregated by country](https://scholia.toolforge.org/topic/Q110983345#country-citation-graph) to clearly distinguish the titles
|Before|After|
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/67158080/155220969-70cf8a09-75bf-4843-b411-a4e48afa8d19.png)|![image](https://user-images.githubusercontent.com/67158080/155221134-008285b2-c14f-4370-8621-a80159a925c8.png)|
> add spacing for citation graph title

- scholia/app/templates/taxon-curation.html
- scholia/app/templates/taxon-curation_missing-topic-tags-for-taxon-name.sparql
Fixes #1903 
Added a curation page to the taxon aspect, with one panel to get started.
We could also indicate TABernacle as a way to do the topic tagging, as per
- #516
- #1268  
and I tried to build that [TABerncale query](https://tabernacle.toolforge.org/?#/tab/sparql/PREFIX%20target%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ202864%3E%0A%0ASELECT%20DISTINCT%20%0A%3Fitem%20%0AWITH%0A%7B%20SELECT%20%20%3Fitem%20%3Ftaxonname%20WHERE%20%7B%0A%20%20target%3A%20wdt%3AP225%20%3Ftaxonname%20.%0A%2 …
> Adding taxon curation page

- scholia/app/templates/organization_employees-and-affiliated.sparql
For the employees and affiliated panel on the the organization aspect,
researchers having authored no works would not show up in the table.
This patch reorder lines in the SPARQL and this apparently helps.
Fixes #1870
Change ordering of lines in SPARQL to make researchers with no authored works show up in employee table in the organization aspect.
* Test A
* Test B
> Fix #1870 organization researcher

- docs/requirements.txt
Fixes #1928
Readthedocs generated an error due dependency on jinja2 details. The downgrades the jinja2 version
* No test
> Fix #1928 readthedocs dependency error

- scholia/app/static/js/citation.js
Update the Citation.js bundle to citation-js 0.5.6 and [plugin-software-formats](https://github.com/citation-js/plugin-software-formats) 0.5.3. See https://github.com/citation-js/plugin-software-formats/issues/12. Bundle content as specified here: https://github.com/WDscholia/scholia/pull/1454
> Update to citation.js 0.5.6 and software-formats 0.5.3

- scholia/app/templates/chemical-index_statistics.sparql
Fixes #1948
Adds the number of chemicals with an NMRShiftDB external identifier.
None.
The query has been tested on the WDQS.
> adds statistics about NMR spectra

- scholia/app/templates/topic_organization-map.sparql
It seems as though the preferred method of storing an organisation's location is by adding a [P625](http://www.wikidata.org/entity/P625) (coordinate location) qualifier on a [P159](http://www.wikidata.org/entity/P159) (headquarters location) statement.
This commit changes the org map query to use the headquarters location by default but still keeps the coordinate location as a fallback.
Relevant discussions:
* https://www.wikidata.org/wiki/Wikidata:Project_chat/Archive/2021/03#coordinate_location_(P625)_to_headquarters_location_(P159)_switch
* https://www.wikidata.org/wiki/Wikidata:Project_chat/Archive/2022/04#DeltaBot's_coordinate_location_(P625)_to_headquarters_location_(P159)_move
> Org map - Use the headquarters location by default

- scholia/app/templates/award-curation_missing-author-items.sparql
Fixes #1977 
added case variants.
Example: https://scholia.toolforge.org/award/Q38104/curation#missing-author-items
Note that the results differ in part due to the ```LIMIT```, in part due to this change.
> adding case variants to award-curation_missing-author-items.sparql

- scholia/app/templates/pathway_participants.sparql
Fixes #1979
Reactome uses a different type (P31) than WikiPathways does (despite the same team behind it).
- biological processes are wider then pathways
Check http://www.wikidata.org/entity/Q50294491 before and after the patch. The second will show parts. https://w.wiki/5C5R
This patch only updates one of the SPARQL queries and no code changes are made.
> Handle Reactome pathways

- scholia/app/templates/base.html
Apologies for the shortest PR ever haha
Basically we don't have placeholder text on the main search element. Most people probably intuit it's function or try interacting with it and figure it out, but we should be explicit.
before:
after: 
I searched the rest of the repository and this is the only input with no placeholder text
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you …
> Add placeholder text to search element

- scholia/app/views.py
- scholia/query.py
Fixes #1955
http://127.0.0.1:8100/doi-prefix/10.1371 redirects to http://127.0.0.1:8100/publisher/Q233358
* Tested for the DOI prefix given
* Tested for invalid DOI prefix, redirects to the …
> Add redirect for doi-prefix as specified

- scholia/app/templates/base.html
Fixes #1908
The issue was that the property page only has three headings and so #1519 a table of contents would not be added. This PR reduces this to 3 headings
* Checked P378
> Change limit to 3 headings to create table of contents

- scholia/app/templates/use-curation.html
- scholia/app/templates/use-curation_missing-co-uses.sparql
Fixes #1899 
Shows missing or few co-uses works on use-curation page
* examined, e.g., http://127.0.0.1:8100/use/Q1635410/curation
> Co-uses for use curation #1899

- scholia/app/templates/event_future-events.sparql
- scholia/app/templates/event_past-events.sparql
Fixes #1715
Fix handling of instances of scientific event so they show up in the event tables.
* Checked that https://www.wikidata.org/wiki/Q109804073 showed up in past events.
> Bug/scientific event as event #1715

- scholia/app/static/scholia.js
- scholia/app/templates/author_venue-statistics.sparql
Fixes #1481
Generally adds the ability for a column to have a label and a URL. Previously they could have only have one.
Specifically link the venue column to the venue aspect
* Checked on the …
> Link venue in venue column

- scholia/app/templates/base.html
Apologies for so many PRs but want to keep them atomic
Right now if you go on the scholia page for the mona lisa, the picture takes awhile to display as the file served by commons is 90MB. Instead with this PR, commons serves a thumbnail which is 500px across and is ~100kb 
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide instructions, so we …
> Serve thumbnail instead of full image

- scholia/app/templates/base.html
Builds on #2028 Fixes #1940
Shows a 500px wide thumbnail instead of a broken image
* Checked the mona lisa page to ensure images still show okay
* Checked the original item of interest to ensure …
> Display TIF images properly

- scholia/app/templates/ask_work_gallery.sparql
- scholia/app/templates/work.html
- scholia/app/templates/work_associated-images.sparql
- tests/test_ask_query.py
Draft as I'm unsure how to access Commons category/gallery images
On the way to closing the issue #187
This PR `ASK`s whether a work has an associated [Commons category (P373)](https://www.wikidata.org/wiki/Property:P373) and then shows a gallery of associated images in the same way as the author image gallery
However displaying images from the category would be better
Property [Commons gallery](https://www.wikidata.org/wiki/Property:P935) (P935) may also be useful
Haven't yet figured out how to access the images from either, **help wanted**
> Please list anything which has been left out of this PR or which …
> Add gallery for works with a commons category

- scholia/app/templates/base.html
- scholia/app/templates/software.html
- scholia/app/templates/work.html
Moves the citation button from below the title/description to next to the "Improve data" button, using a new block `page_actions`.
Using the `page_actions` block currently requires calling `{{ super() }}`, otherwise the "Improve data" button disappears.
- Go to a work page and click the "Cite" button
- Repeat for a software page
> Move cite button to top row

- scholia/app/templates/organization-topic_authors.sparql
Fixes #2048 
I added the missing question mark, and the example page https://scholia.toolforge.org/organization/Q1269766/topic/Q35 now renders properly:
> added missing question mark

- scholia/app/templates/work-curation_author-resolving.sparql
Fixes #2050 
moved the INCLUDE %authors to the ?author part of the UNION 
Test page: https://scholia.toolforge.org/work/Q56490640/curation
Screenshot after fix:
> adjust work-curation_author-resolving.sparql to account for case when work has no P50 statement

- scholia/app/templates/work_statements.sparql
Fixes #2046 
Added a line to filter out the qualifier values.
Screenshot of ```/work/Q112339024```:
> filtering out the qualifier values in scholia/app/templates/work_statements.sparql

- scholia/app/templates/index.html
- scholia/app/templates/organization-index.html
- scholia/app/templates/organization-use.html
- scholia/app/templates/organization-use_authors.sparql
- scholia/app/templates/organization-use_recent-literature.sparql
- scholia/app/templates/organization.html
- scholia/app/templates/organization_uses.sparql
- scholia/app/views.py
Fixes #2058 
This provides a way to browse organization-related information about the use of research resources. It is modeled after the existing organization/ topic subaspect.
See examples from …
> Added an /organization/QID1/use/QID2 subaspect

- scholia/app/views.py
Fixes #2079
Fixes styling errors
There are still some test errors in tox for python3.8 and python3.9
`pycodestyle scholia` runs ok. 
`tox py38` does not run ok
> Fix #2079 Too long doc lines

- scholia/app/templates/venue.html
- scholia/app/templates/venue_retractions.sparql
Implements #2088 
Adds a panel to list the retracted articles in this journal
No code changes.
Tox tests with Python3.9 show no problems:
```
_________________________________________________________________________________________________________________________________________ summary _________________________________________________________________________________________________________________________________________
flake8: commands succeeded
pydocstyle: commands succeeded
ERROR:  py37: InterpreterNotFound: python3.7
ERROR:  py38: InterpreterNotFound: python3.8
py39: commands succeeded
```
> Adds a panel to list the retracted articles in this journal

- scholia/app/templates/index-statistics_statistics.sparql
Fixes [# (issue number, if applicable) ](https://github.com/WDscholia/scholia/issues/2085)
Make a small addition to the Statistics table to list the number of retracted articles.
I ran the query and it does not add significant time to the query and still runs within about 1.2 seconds.
I ran the query on the WDQS.
> Added another query to list the number of retracted articles

- scholia/query.py
After PR #2099 some redirects did not work.
Fixes #2103 
After PR #2099 some redirects did not work.
I tested a few cases
> Fix #2103 Fix bad redirects

- scholia/app/static/scholia.js
Fixes #2037
This was a great bug to catch! As of now when a query with a count column returns no matches it errors and loads forever:
I have instead added a message to communicate to the user
Additionally I have removed the loader when the query fails
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide instructions, so we can reproduce. Please …
> Add message when query returns no matches

- scholia/app/templates/event.html
Fixes #2060 
I did not go for "attendees" (which was suggested in the issue) because some co-authors often were not actually *attending* the event, but I think co-authoring a paper presented there still makes them participant of some sort, and the corresponding Wikidata property ([P710](https://www.wikidata.org/wiki/Property:P710)) has the English label "participant".
I just changed the HTML section title, leaving the section id intact.
> Change "Co-author graph" to "Co-author graph of event participants"

- scholia/app/templates/chemical-class.html
- scholia/app/templates/chemical-class_found-in-taxon.sparql
The changes include a new table on the `chemical class` page.
Motivation is to access taxa producing specific chemical classes.
* No specific tests, just the ones of the CI
> Adding chemical classes found in taxa

- scholia/app/templates/topic_uses.sparql
This is a simple replacement of one expression with another that achieve identical functionality in terms of the Scholia content to be displayed but differ in that the new version makes it easier to adapt the query to another QID.
There are probably a number of similar cases throughout the code base, which I have not explored.
* Go to https://scholia.toolforge.org/topic/Q202864#uses
Table looks as expected:
Click on "Wikidata Query Service" and …
> replace {{ q }} expression with target: expression in topic_uses.sparql

- setup.py
This uses entrypoints to create a vanity CLI, so rather than needing to do `python -m scholia ...`, you can just do `scholia ...`. To test this code, you must reinstall Scholia, entrypoints do not get updated on editable installations without doing `pip install .` or `pip install -e .` again.
There was previous discussion about this in https://github.com/WDscholia/scholia/pull/1471 but for some reason there were issues. I'm hoping that now the project has modernized a bit that this is non-controversial.
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran …
> Create vanity CLI

- scholia/app/static/css/scholia.css
- scholia/app/static/scholia.js
Will fix the issue #886 partially
To do:
Result: 
The loader briefly appears and the page looks the same when the reload button is clicked
When there is no header it appears just before it in the HTML
Without `clear: both` on `H3` we have:
I've added it so instead we have
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide instructions, so we can …
> Add refreshing of data tables

- scholia/app/templates/software-index_most-used-software.sparql
The "most used software" aspect in the software index used the P2283 propety. The more relevant property would be P4510.
Fixes #2118
Single line change in SPARQL query
* I checked http://127.0.0.1:8100/software/
> Fix #2118 software index used wrong property

- scholia/app/templates/software-index_most-used-software.sparql
"Software" column in "most used software" panel on the software index page did not direct to the appropriate 'software' aspect. It now does.
Fixes #2120
Include a explicit ?softwareUrl for the link.
* Checked http://127.0.0.1:8100/software/
> Fix #2120 link in software index

- scholia/scrape/ojs.py
- tests/test_scrape_ojs.py
Now one-page OJS articles are display with only a single number
Fixes #1233
Change from, e.g., "11-11" to "11"
* Pull request includes a new test file
* `scholia.scrape.ojs.scrape_paper_from_url("https://tidsskrift.dk/stenomusen/article/view/120902")`
> Fix #1233 1-page OJS articles

- .github/ISSUE_TEMPLATE/add-new-aspect.md
- .github/ISSUE_TEMPLATE/add-new-panel.md
- .github/ISSUE_TEMPLATE/modify-a-sparql-query.md
- .gitignore
- scholia/app/static/css/nightmode.css
- scholia/app/static/css/scholia.css
- scholia/app/static/scholia.js
- scholia/app/templates/base.html
- scholia/app/templates/chemical-class.html
- scholia/app/templates/chemical-class_found-in-taxon.sparql
- scholia/app/templates/chemical.html
- scholia/app/templates/event.html
- scholia/app/templates/event_presentations.sparql
- scholia/app/templates/index-statistics_statistics.sparql
- scholia/app/templates/software-index_most-used-software.sparql
- scholia/app/templates/topic_uses.sparql
- scholia/app/templates/use_authors-of-works-using-the-resource.sparql
- scholia/app/templates/use_co-used.sparql
- scholia/app/templates/use_recent-work-using-the-used.sparql
- scholia/app/templates/use_topics-of-works-using-the-resource.sparql
- scholia/app/templates/use_usage-over-time.sparql
- scholia/app/templates/venue.html
- scholia/app/templates/venue_retractions.sparql
- scholia/app/views.py
- scholia/query.py
- scholia/scrape/ojs.py
- setup.py
- tests/test_scrape_ojs.py
Fixes #2070
Added LIMITs to most of the queries and subqueries on the use aspect
The use of LIMITS in the (usually unsorted) subqueries means that once those limits are reached (and some are already), then relevant results will not be included in the visualizations. In such cases, it may be more useful to actually have a random selection via something like 
```SPARQL
SERVICE bd:sample { ?work wdt:P4510 target: . bd:serviceParam bd:sample.limit 100000 }
``` …
> Limits for use profile 2070

- scholia/app/templates/work_wikipedia-mentions.sparql
This change still does not search across all Wikipedia, but only adds one more Wikipedia to search.
Fixes #2109
This is only a partially implementation of #2109. Only Portuguese Wikipedia is added to search.
* http://127.0.0.1:8100/work/Q22242083#wikipedia-mentions
> Fix #2109 add Portugese to Wikipedia mention table

- scholia/app/templates/work_list-of-authors.sparql
Extended the definition of when the academic age begins: Before it was a scholar article, now it is a subclass of scholarly work, so, e.g., conference articles also counts.
Fixes #2136
See above
* http://127.0.0.1:8100/work/Q24319057
> Fix #2136 for negative academic age

- scholia/app/templates/work_list-of-authors.sparql
- scholia/qs.py
- scholia/scrape/ceurws.py
Fixes #1438
Scraper for CEUR Workshop Series. The scraper has not been tested on all volumes. Perhaps early proceedings will fail.
* For instance `python -m scholia.scrape.ceurws proceedings-url-to-quickstatements http://ceur-ws.org/Vol-2982/`
> 1438 scraper for ceur workshop proceedings

- scholia/scrape/ceurws.py
Fixes #2139
CEUR scrape could err when the 'CEURVOLACRONYM' was not set on the page. Now there is a workaround.
*  `python -m scholia.scrape.ceurws proceedings-url-to-quickstatements http://ceur-ws.org/Vol-3246/` works
> Fix #2139 acronym CEUR scraper

- scholia/scrape/ceurws.py
- scholia/scrape/ojs.py
- scholia/utils.py
CEUR WS scraper did not scrape authors on http://ceur-ws.org/Vol-1191/ CEUR WS scraper now extract pages and computes number of pages An extract error appeared for http://ceur-ws.org/Vol-3240/. This is corrected.
Fixes #2143 and fixes #2141
See above
* `python -m scholia.scrape.ceurws proceedings-url-to-quickstatements http://ceur-ws.org/Vol-3240/`
> Fix #2143 and fix #2141 CEUR scraping errors

- scholia/app/templates/chemical-element.html
- scholia/app/templates/chemical-element_data.sparql
The `chemical-element` aspect did not have a data panel yet. I created one now with four fields of information:
(for https://scholia.toolforge.org/chemical-element/Q623)
I ran `tox` with Python 3.9 and this gave no problems:
```
________________________________________________________________________________________________________________________________________ summary _________________________________________________________________________________________________________________________________________
flake8: commands succeeded
pydocstyle: commands succeeded
ERROR:  py37: InterpreterNotFound: python3.7
ERROR:  py38: InterpreterNotFound: python3.8
py39: commands succeeded
```
> Adds a chemical-element data panel

- scholia/app/templates/work_data.sparql
Fixes #2147
I added a row to the data panel that shows a link to the preprint. It uses the pattern `wdt:P31 'preprint'` with the `of` qualifier (in reverse).
The result should now look for `/work/Q114821829` like:
> Link works to their (in Wikidata existing) preprints in the data panel

- scholia/app/templates/work_data.sparql
Fixes #2146 
The updated query checks if the `of` qualifier is given used in the 'preprint of' field.
How to check:
* control that now only the 'preprint of' is visible: `/work/Q98577324`
* check to see the 'Preprint' lines shows up when no `of` is given: `/work/Q1324573`
Screenshots of the expected behavior:
I cannot think of caveats.
> Exclude this 'preprint' field when the 'preprint of' field is

- scholia/app/static/js/citation.js
- scholia/app/templates/work-export.html
Fixes #1971  
Fixes #2083  
See #1594  
- Two additional formats are listed among the export options: EndNote .enw files, and Wikipedia templates.
- Empty strings are no longer treated as valid values in QuickStatements output.
[Bundle configuration](https://juniper-coat.glitch.me/):  
* Go to http://127.0.0.1:8100/work/Q112075162/export
* Select ENW, check output
* Select Wikipedia Templates, check output
> Add formats, fix bugs in work export

- scholia/qs.py
In OJS scrape, and and possibly other cases, strings to quickstatements may have a tab or trailing spaces that will confuse quickstatements. This commit normalize the string for title and author before generating the quickstatement line. Furthermore if the string contains double quotes the previous code generated wrong quickstatements with a wrong kind of escape. No escape seems to be necessary and it has been removed.
Fixes #2178, , #2168 and #2177
*If you …
> Fix #2178, #2168 and #2177 in quickstatement

- scholia/app/static/scholia.js
- scholia/app/templates/404-doi.html
- scholia/app/templates/author-index.html
- scholia/app/templates/base.html
- scholia/app/templates/use.html
Fixes #1661
**Before and afters**
1. If summary fails, display enwiki link
2. Wikiversity
3. If search is unresponsive it will say "Search failed" in the autocomplete rather than showing nothing
4. If ask query fails it will hide the panels rather than showing them
3. Use `console.error` rather than `console.log` for error messages
5. Make sure all ajax calls have a `.fail` or `error:`
Please describe the …
> Add error handling to fetch and ajax calls

- scholia/app/templates/cito-index_articles-by-year.sparql
Right now, this query report the number of articles with CiTO annotation over time and since recently typed by whether or not the article itself provided explicit citation intentions:
This patch updates this to not report `in article` but report the venue with the explicit annotations in the article. The point of this is to visualize the uptake of explicit annotation by venues:
(I can imagine that in the future when this has become commonplace, we will depict this quite differently again)
> Report venue is CiTO annotation source

- scholia/app/templates/index.html
Following the normal procedure, adding a `<link rel="me">`  line to authenticate our link to the Mastodon account.
See more at, for example, https://til.simonwillison.net/mastodon/verifying-github-on-mastodon
> Authenticate the new Mastodon account

- scholia/app/templates/use-curation_missing-author-items.sparql
Fixes #2194
This adds some SPARQL limits to the query in order to improve performance within the constraints of the Wikidata Query Service. Also slightly rearranged the result ordering to emphasize the use-related author string curation over curation of the strings more generally.
Comparse https://scholia.toolforge.org/use/Q1659584/curation#missing-author-items with the …
> adding LIMITs to use-curation_missing-author-items.sparql 

- requirements.txt
Security issue for certifi is present for earlier versions: CVE-2022-23491. Now a newer version of certifi is explicitly stated
Fixes #2202
Explicit upgrade of certifi.
* Ran a pip install 
* Test B
> Add rule for certifi

- scholia/app/templates/event.html
- scholia/app/templates/event_data.sparql
Fixes #2206 
Adds a data table with event series, short name, and organizers.
I can imagine more info will be requested in the future to be added in the data table, like start/end data, venue, etc.
Run the patched Scholia locally and go to http://127.0.0.1:8100/event/Q48027575
It should look like this:
> Adds an 'event' data table, with link to the event series

- scholia/app/templates/taxon.html
- scholia/app/templates/taxon_co-occurring-taxa.sparql
Fixes #2161
On the taxon profile, added a panel about taxa co-occurring with the target taxon in the literature.
* Good taxa to test this with:
* Q25419 (Escherichia coli)
* Q202864 (Zika virus)
> On taxon profile, add panel about co-occurring taxa 

- scholia/app/templates/chemical.html
Fixes #1942
Renames the section as suggested in the issue.
None.
* check https://scholia.toolforge.org/chemical/Q3613679#Related
> Renamed the "Related Compounds" section into "Compounds with same connectivity"

- scholia/query.py
Map items of type [Q110716513](http://www.wikidata.org/entity/Q110716513) (scholarly letter/reply) to the "work" aspect, instead of the default "topic" aspect.
For example, when searched for, [Q28661563](http://www.wikidata.org/entity/Q28661563) should take you to [/**work**/](https://scholia.toolforge.org/work/Q28661563), instead of [/**topic**/](https://scholia.toolforge.org/topic/Q28661563).
* See [this discussion](https://www.wikidata.org/wiki/Wikidata_talk:WikiProject_Source_MetaData/Archive_6#Letters_to_the_editor) for more information on the type.
* See [this list](https://w.wiki/6G3W) to assess type usage.
While the current usage is very small (67 items at the time of writing), it has still proved to be useful and I expect increased adoption in the future. At the moment, most of …
> Map "scholarly letter/reply" items to work aspect

- scholia/app/templates/chemical.html
Fixes #2226
The HTML had two `@id` attributes on various elements.
> Removed redundant @id attributes

- scholia/app/templates/protein_participates-in.sparql
Fixes #1606
The column header was still mentioning just "complex" but now matches the description.
None reported.
* visit `/protein/Q88656943` and notice that the 2nd column header now writes `Complex or process`:
> Match the column header with the description (and query)

- scholia/app/templates/cito-index.html
- scholia/app/templates/cito-index_cited-journal-counts.sparql
New feature.
We already had a table [Journals and how many CiTO-annotated citations they have](https://scholia.toolforge.org/cito/#journal-counts) table, and this patch adds the equivalent table for cited journals.
* Check http://127.0.0.1:8100/cito/#cited-journal-counts (the number of rows should match the the top table, ~165)
> Added a table with the journal receiving annotated citations

- scholia/app/templates/chemical-index_statistics.sparql
Small patch: when calculating the number of crystal structures, compounds with a CSD Refcode can be counted too. This property was accepted this week.
Potentially, a more complex makes the query not run fast enough, but this does not seem to be the case
(not noticeable ).
Visit https://scholia.toolforge.org/chemical/ (before/after)
* [ x I have not used code from external sources without attribution
> New property for crystal structures, new statistics

- scholia/app/templates/404-chemical_related.sparql
Fixes #2223
This patch add the use of the `wikibase:mwapi` to speed up the query by at least on order of magnitude.
None observed.
Compare old versus new:
* old: https://w.wiki/6Drq
* new: https://w.wiki/6Dro
> Use the wikibase:mwapi to find InChIKeys

- scholia/app/static/scholia.js
- scholia/app/templates/404-chemical.html
The PR #2224 cause a variable not to be interpolated. Furthermore the header was missing and the table does not appear if there is not a h2, h3 or h4 section header.
Fixes #2247
This should fix issues with #2224 where the related table in the 404 page for a chemical did not show.
* http://127.0.0.1:8100/inchikey/KDXKERNSBIXSR
> Fix #2247 related table in 404 chemical show

- scholia/app/templates/cito-index.html
- scholia/app/templates/cito-index_articles.sparql
A new feature and does not fix anything.
This patch add a table with recent articles with explicit CiTO annotations. If CiTO does not see further uptake, this table with get more boring over time. For now, this is a nice way to find articles with explicit CiTO annotation.
This patch updates the `/cito/` page:
* https://scholia.toolforge.org/cito/
> There are enough articles now to have a table with recent articles with explicit CiTO annotations

- scholia/arxiv.py
Fixes #2232
Converted P820 claims from stand-alone statements to qualifiers on P818 statements
Errors in the P820 part (e.g. missing classifications) might affect the P818 statement. This is not handled yet.
1. Check out recent arXiv papers (e.g. via [this query](https://arxiv.org/search/advanced?advanced=&terms-0-operator=AND&terms-0-term=climate&terms-0-field=title&classification-physics_archives=all&classification-include_cross_list=include&date-filter_by=past_12&date-year=&date-from_date=&date-to_date=&date-date_type=submitted_date&abstracts=show&size=50&order=-announced_date_first)), pick one that looks suitable for Wikidata and copy its arXiv ID (```2301.04253``` in my case)
1. Paste that arXiv ID into …
> arXiv classification P820 as qualifier to arXiv ID P818

- scholia/app/templates/work_data.sparql
Fixes #1597 and fixes #1886
The first (oldest) patch fixes the problem reported in both bug reports. The second (newer) patch implements the suggestion reported in the https://github.com/WDscholia/scholia/issues/1597#issuecomment-898766620 comment (and the similar for retractions). 
There are no code changes.
Suggested to test the following pages with various situations, which before/after sometimes differs, demonstrating what is fixed:
* https://scholia.toolforge.org/work/Q24613508
* https://scholia.toolforge.org/work/Q24564615
* https://scholia.toolforge.org/work/Q114679534
* https://scholia.toolforge.org/work/Q102319086
* https://scholia.toolforge.org/work/Q102092244
> Fixing an issue and implements a feature request around linking versions of papers

- scholia/app/templates/author-curation.html
- scholia/app/templates/author-curation_missing-use-as-reference.sparql
- scholia/app/templates/base.html
Fixes #2213 
This patch adds a panel to an author curation page, listing works for that author that do not support any
statements.
No caveats I can foresee.
Test is with any author with multiple articles. The output should look something like this:
> Panel for the author curation page to list articles that are not used as reference for any statement

- scholia/app/templates/series_works.sparql
Citation count in "published works" panel in series aspect counted wrong (double?). This is now fixed.
Indentation has also been changed.
Fixes #2264
- Add DISTINCT
- Change indentation
* http://127.0.0.1:8100/series/Q924044
> Fix #2264 citation counts in series

- scholia/app/templates/chemical_related.sparql
Earlier this year we improved the speed of the InChIKey 404 page (https://github.com/WDscholia/scholia/commit/eec1eebf226de1fed9d1978f8c4ed350a74b7793), and this patch migrates that idea to the `chemical/` aspect.
This patch uses `wikibase:mwapi` to significantly speed up the listing of chemical structures with the same chemical connectivity. This happens in three steps (using SELECT-WITH-WITH-WHERE). The first step asks for the InChIKey for the target chemical and prepares the search strings. The second step uses the prepared search strings to use `wikibase:mwapi` to find related InChIKeys and a `FILTER` to remove false positives. The last steps adds looking up some additional information for the found chemicals.
One caveat is the further dependency on the Blazegraph backend, but that's …
> Speeding up 'Compounds with same connectivity' query on the chemical/ pages too

- scholia/scrape/ojs.py
Fixes #2274
Fix #2274 extended OJS scraper for article URLs: The scraper for Open Journal System did not work for https://www.journals.vu.lt/scandinavistica/issue/view/1153
I have not been able to test the code locally with all of the tox rules.
* `python -m scholia.scrape.ojs issue-url-to-quickstatements https://www.journals.vu.lt/scandinavistica/issue/view/1153` and …
> Fix #2274 extended OJS scraper for article URLs

- scholia/query.py
Currently, [drinks](http://www.wikidata.org/entity/Q40050) are mapped to the 'chemical-class' aspect; I think that items with this parent would be better off defaulting to the 'topic' aspect. This commit makes that so.
There may be instances where this would not be ideal, but I'm not aware of any. Thoughts by people more familiar with  chemistry would be much appreciated!
I have tested this change using Gitpod.
Local changes can be tested with this URL (using [whisky](http://www.wikidata.org/entity/Q281) as an example):
* http://127.0.0.1:8100/Q281
> Map subclassed items of drink to the topic aspect

- scholia/query.py
The OpenAlex identifier for an author was changed in Wikidata. That identifier was used in a doctest for Scholia, so the doctest failed. This fix change the test to another person with an apparently more stable OpenAlex identifier.
Fixes #2282
The OpenAlex identifier for an author was changed in Wikidata.
That identifier was used in a doctest for Scholia, so the doctest
failed. This fix change the test to another person with an
apparently more stable OpenAlex identifier.
Not tested!
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your …
> Fix #2282 Change doctest for identifier change

- scholia/app/templates/work_data.sparql
- scholia/query.py
A US patent now defaults to 'work' aspect
The type of the work is now shown in the top data panel
Fixes #2278
Completes two environments. Two of my other environments does not work.
* …
> Fix #2278 US patent handling

- scholia/app/templates/cito-index_statistics.sparql
New feature.
Besides journal articles and individual annotations, there are also datasets with explicit CiTO annotation, e.g. as the outcome of a literature study. This addition uses a new Wikidata item for datasets with explicit CiTO annotation, allowing us a way to track them. There are three that I currently know of, two of which are in Wikidata.
None that I can think of.
* open https://scholia.toolforge.org/cito/ and notice the extra line:
> Added the number of datasets with explicit CiTO annotations

- .github/workflows/main.yml
- tox.ini
Work in progress. This PR adds Python 3.10 so that we have a clear overview of the problems, fix them one by one, until all is solved.
Intention: Fixes #2183
Scholia is reported to not compile/run with Python 3.10. 
No new code is introduced.
> Add Python 3.10 to the testing workflow

- .github/workflows/docker-image.yml
- .github/workflows/main.yml
Version `v3` of the GitHub Action updates the Nodejs version (from 12 to 16), see https://github.com/actions/checkout and https://github.com/actions/setup-python
Needed according to compile warnings:
> Updated actions/checkout and actions/setup-python

- scholia/app/templates/wikiproject.html
- scholia/app/templates/wikiproject_co-occurring.sparql
- scholia/app/templates/wikiproject_topics.sparql
Daniel mentioned that it would be useful to see co-occurring WikiProjects like we do with co-occurring topics on the topics aspect
* Test A
* Test B
> Add co-occurring WikiProject panel

- scholia/scrape/ceurws.py
CEUR-WS scraper failed where metadata had a element for pages but this was empty.
Fixes #2317
Test on empty string for empty pages in pages element in scraped page for CEUR-WS
* `python -m scholia.scrape.ceurws proceedings-url-to-quickstatements https://ceur-ws.org/Vol-3443/`
> Fix #2317 empty pages CEUR-WS scraper

- scholia/app/templates/author_most-citing-authors.sparql
- scholia/app/templates/dataset_list-of-authors.sparql
- scholia/app/templates/topic_authors.sparql
- scholia/app/templates/wikiproject_authors.sparql
- scholia/app/templates/work-curation_missing-orcid.sparql
Fixing same issue as Daniel's PR here https://github.com/arthurpsmith/author-disambiguator/pull/187
ORCID changed their search URL so we need to use a different structure. I searched for all occurrences in the repository and fixed them
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide instructions, so we can reproduce. Please also list any …
> Fix ORCID URL after structure was changed

- scholia/utils.py
Python 3.10 flake8 style would not accept the previous form.
Fixes #2322
One-line fix for style
python 3.7 and 3.8 did not pass. Python 3.7 probably an remote access issue, 3.8 because lack of Interpreter.
* Test A
* Test B
> Fix #2322 type comparison for q id

- scholia/query.py
See https://www.wikidata.org/wiki/Wikidata:WikiProject_Chemistry/Guidelines/Basic_metaclasses_and_relations#Basic_metaclasses_for_chemical_entities
This is urgent because the use of 'chemical compound' is being phased out, and most chemical compounds would map to the `/chemical-class/` aspect instead of the correct `/chemical/` aspect.
This patch updates the matching by Scholia to the correct chemical aspects. It also updates the label of two classes.
The following CLI call should give the following replies:
```shell
(scholia) ~/var/Projects/hub/scholia$ python -m scholia.query q-to-class Q899008
chemical
(scholia) ~/var/Projects/hub/scholia$ python -m scholia.query q-to-class Q425061
chemical_class
(scholia) …
```
> Implement the new chemical entity structure

- scholia/app/templates/index-statistics.html
Does not immediate fix something, but linking to the general Wikidata Statistics pages seems to make sense.
Adds the link and slightly rewrites the text accordingly.
I am not 100% happy with the text. Please improve the text if you feel needed.
Visit https://scholia.toolforge.org/statistics and test the link.
> Link to Wikidata statistics page too

- scholia/app/templates/venue_recently-published-works.sparql
Not a fix, just a more performant query. The problem was that the list of recent articles for [Nature](https://scholia.toolforge.org/venue/Q180445#recently-published-works):
This patch applies our common solution of WITH/AS in the SPARQL query.
* https://scholia.toolforge.org/venue/Q180445#recently-published-works should now complete in under 20 seconds
> Faster query: applied WITH/AS/WHERE to postpone looking up labels and author info

- scholia/app/templates/work-index.html
- scholia/app/views.py
- scholia/query.py
Fixes #284
Adds the `Random` button for works.
* The default comes from the `/work/` index page
* I wonder if the `random_x` method can be generalized
* Open http://127.0.0.1:8100/work/random twice
* Check the presence of the blue `Random` button on http://127.0.0.1:8100/work/
> Implemented random work

- scholia/app/templates/chemical-curation.html
- scholia/app/templates/chemical-curation_missing-main-subjects.sparql
- scholia/app/templates/chemical-curation_missing-properties.sparql
* implements #1909 
Curation page for chemicals.
* test the curation page for L-proline: http://127.0.0.1:8100/chemical/Q20035886/curation
> Added a curation page for /chemical/

- scholia/app/templates/work_data.sparql
Fixes #249
Fixes #491 
There is a `replies to` property and the linked issue requests adding that info. I added it to the data table.
None that I can think of (right now).
* http://127.0.0.1:8100/work/Q28951838
* http://127.0.0.1:8100/work/Q56377493
> Added support for 'replies to' in the data table

- scholia/app/templates/disease-index.html
- scholia/app/views.py
- scholia/query.py
Addresses #924
Adds a modern index page and redirection for OMIM identifiers:
Only implements one of the suggested redirects.
* Go to http://127.0.0.1:8100/disease/ and check if it looks like the above screenshot
* Click the redirect which should lead to https://scholia.toolforge.org/topic/Q191779
> Disease index page and OMIM redirect

- scholia/app/templates/chemical-class.html
- scholia/app/views.py
Fixes that the 'chemical-class' aspect did not show SMILES, even tho SMILES and CXSMILES can be given and can be depicted.
Now also shows (CX)SMILES in the `chemical-class` aspect:
Functionality that already existed for the `chemical` aspect and is just ported here.
* http://127.0.0.1:8100/chemical-class/Q120868227
> Also depict (CX)SMILES for chemical classes

- scholia/app/templates/chemical-index_statistics.sparql
Doesn't really fix anything, but just does a bit more justice to the hard work of people.
Adds statistics on these properties:
- dipole moment
- ionization potential
- safety info
Check https://scholia.toolforge.org/chemical/
> Report more chemical properties

- scholia/app/templates/chemical-index-curation_missing-boiling-points.sparql
... and likely don't have a boiling point defined.
Improves the physchem properties curation page which e.g. shows CO2 which does not have a boiling point:
This patch adds a filter for compounds that have a sublimation point defined.
Visit https://scholia.toolforge.org/chemical/curation and confirm CO2 is no longer listed as missing a boiling point.
> Exclude compounds that sublimate

- scholia/app/templates/organization_advisor-graph.sparql
Fixes #2347
Adds the suggestion OPTIONAL and DISTINCT
Compare http://127.0.0.1:8100/organization/Q24283660 before and after the patch. 
More people should show up:
> Gender should not be required, and reduced the amount of data passed around

- scholia/app/templates/chemical-class_related-chemicals.sparql
Fixes #2343
This patch updates the SPARQL query to find example compounds. 
The problem arose (apparently) from a model change where `subclass` is predominantly used, not `is a`.
* Go to https://scholia.toolforge.org/chemical-class/Q648037#related-chemicals
* See a filled table
> Update query for chemicals in a compound class

- scholia/app/templates/chemical-class_class-hierarchy.sparql
- scholia/app/templates/chemical-class_publications-per-year.sparql
- scholia/app/templates/chemical-class_recent-literature.sparql
- scholia/app/templates/chemical-class_related-chemicals.sparql
Fixes various issues, including the visual hierarchy plot. Continues the patch in another panel: https://github.com/WDscholia/scholia/pull/2344
Previously, specific chemicals where `instance of` a chemical class, but they are now always `subclass of`. To continue the differences in the `chemical-class` aspect, we need to do this check differently. Some updates do this by checking if the subclass itself has subclasses, mimicking the `P31` behavior before. In other places, the `P31` can just be removed because it used "one or more". For those panels, we do not see differences.
After the patch, some of the nodes should be orange again:
* …
> more chemical-class updates for the updated Wikidata chem hierarchy model

- scholia/app/templates/chemical_found-in-taxon.sparql
Fixes #2354
The column name is case sensitive when recognized as linkable.
Doesn't look so pretty. Maybe the core that adds the link can also recognize "DOI" is column name. But that needs testing as it is used elsewhere.
* Check if that taxon section (e.g. https://scholia.toolforge.org/chemical/Q209284#found-in-taxon) has clickable DOIs
> Ensure the DOI gets linked

- scholia/app/templates/dataset-export.html
- scholia/app/templates/dataset.html
- scholia/app/views.py
Implements #2325
Adds the `Cite` button to the `dataset` aspect.
* https://scholia.toolforge.org/dataset/Q120320769
* https://scholia.toolforge.org/dataset/Q120320769/export
> Implement 'Cite' for datasets

- scholia/app/static/scholia.js
- scholia/app/templates/taxon_metabolome.sparql
Fixes #1427
Added some more Scholia logic to "recognize" `*ChemicalStructure` columns and then expects a SMILES (canonical or isomeric) and will use the Toolforge CDK Depict instance to display the 2D structure. The column gets renamed to `* structure` (like with `*Description`).
There is a change (like with `*Label`) that we accidentally use if for something other than SMILES (rare, I expect).
The patch uses this new functionality on the `taxon` page:
* Try pinus: http://127.0.0.1:8100/taxon/Q12024#metabolome
> Like *Label, *ChemicalStructure is a new special, expects a SMILES and will use CDK Depict (Toolforge) to visualize the chemical structure in 2D

- scholia/app/templates/base.html
Fixes #2368
Add an base menu item for the index page for WikiProjects.
* Go to the Scholia front page
* Open the Project menu
* Check if WikiProject is listed:
> Added the WikiProject index to the menu

- scholia/app/templates/chemical-index_statistics.sparql
Fixes #2377
> This PR modifies the query for the statistics displayed on the chemical index page. It uses Cirrus Search for efficiency reason and limits the results to chemicals by their P31 property. This way, some other items not corresponding to chemicals using similar properties will not be listed (minerals, proteins, etc.). Further, it allows to display statistics that were not displayed before for the exact same reason.
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide instructions, so we can reproduce. Please also …
> Statistics for chemical index aspect

- scholia/app/templates/index-statistics_statistics.sparql
Hi Finn, this is a question if an enhancement list this makes sense. It's doesn't seem to slow down the query and answers the worry that articles are the major part of the Wikidata items.
> Count all unique items with a P31

- scholia/app/templates/chemical-class_found-in-taxon.sparql
Taxa panel in chemical class aspect did not show a chemical class if the taxa was annotated with the chemical class - as oppose to a chemical in the chemical class.
Further change is taxon description, column renaming and example chemical.
Fixes #2367
SPARQL query change from `wdt:P279+` to `wdt:P279*` and some further edits.
* …
> Fix #2367 Expand taxon-chemical-class query

- scholia/scrape/ceurws.py
If there was a newline in the title of the CEURWS proceeding then wrong Quickstatements would be generated.
This fix normalize consecutive whitespace to one normal space.
Fixes #2386
see above
* `ython -m scholia.scrape.ceurws proceedings-url-to-quickstatements https://ceur-ws.org/Vol-3559/` went through alright
> Fix #2386 title issue in CEURWS scraper

- scholia/app/templates/base.html
This patch removes user-visible links to X/Twitter.
There may be more left. These can be filed a separate bug reports.
Workflows that depending on looking up Twitter accounts via the web interface will break (but that's intentional).
Without the patch, it currently looks like this:
After the patch, the link and logo for the X social account is gone.
> Removed visible links to Twitter

- scholia/app/static/js/citation.js
Update the Citation.js bundle to v0.7.8. Bundle content as specified here: https://github.com/WDscholia/scholia/pull/2151. This fixes the issue of SICI-style DOIs (#2406), and also includes a patch that improves non-ASCII escaping in BibTeX output.
> Update Citation.js to 0.7.8

- scholia/app/views.py
Fix #2406 DOI pattern for DOIs with square brackets
Fixes #2406
Extended regular expression with square brackets
* Saw that [10.1641/0006-3568(2002)052[0044:PTLBTR]2.0.CO;2](https://doi.org/10.1641/0006-3568%282002%29052%5B0044%3APTLBTR%5D2.0.CO%3B2) worked
> Fix #2406: DOI pattern for DOIs with square brackets

- scholia/app/templates/base.html
- scholia/app/templates/podcast-episode.html
- scholia/app/templates/podcast-episode_data.sparql
- scholia/app/templates/podcast-episode_guests.sparql
- scholia/app/templates/podcast-episode_listings.sparql
- scholia/app/templates/podcast-index.html
- scholia/app/templates/podcast-index_languages.sparql
- scholia/app/templates/podcast-language.html
- scholia/app/templates/podcast-language_podcast-list.sparql
- scholia/app/templates/podcast-language_recent-episodes.sparql
- scholia/app/templates/podcast-season.html
- scholia/app/templates/podcast-season_data.sparql
- scholia/app/templates/podcast-season_episodes.sparql
- scholia/app/templates/podcast.html
- scholia/app/templates/podcast_data.sparql
- scholia/app/templates/podcast_listings.sparql
- scholia/app/templates/podcast_recent-episodes.sparql
- scholia/app/templates/podcast_seasons.sparql
- scholia/app/templates/podcast_topics.sparql
- scholia/app/views.py
- scholia/query.py
See https://github.com/WDscholia/scholia/issues/2414
Implements aspects for podcasts.
The current PR has reasonable stubs, but particularly the `podcast episode` aspect is a bit boring right now.
The current PR causes a Codacy warning for a line of code where a random call is made for the "Random podcast" button, following the approach of other random buttons:
I assume this risk is acceptable. I cannot think of an attack using this approach, e.g. allowing people to also end up on an advertisement item in Wikidata. Nor worse.
The `podcast` index page has a number of examples: http://127.0.0.1:8100/podcast/ (see below screenshot)
> three new aspects: podcast. - episode, and - season)

- scholia/app/templates/podcast-index_languages.sparql
- scholia/app/templates/podcast_data.sparql
- scholia/app/views.py
Fixes #2422
Changes the URL pattern for the page about podcasts in a certain language. See the request in the issue report.
I scanned the code and tests the local live instance, and I think I got all the places where the URL pattern is used. This is in the routing table, but also in two places where there is a link to the language.
* Go to http://127.0.0.1:8100/podcast/Q124262264 (and notice the `Dutch` language in the data table)
* Click the language link to http://127.0.0.1:8100/language/Q7411/podcast
Before this patch, it linked to https://scholia.toolforge.org/podcast/language/Q7411 which is should not anymore.
> Implement different podcast language page URL pattern

- scholia/scrape/ojs.py
Fixes #2420
This PR modifies the code to ensure that article titles containing a dash are only replaced with a colon if the article is not identified. If the article is identified after the modification, the modified title is used; otherwise, the original title with the dash is retained.
No caveats.
1. Test with an identified article containing a dash in the title.
2. Test with an unidentified article containing a dash in the title.
3. Verify that the title modification behaves as expected in both cases.
> Ensure Article Titles with Dashes are Handled Appropriately for Identified Papers

- scholia/app/static/scholia.js
- scholia/app/templates/podcast-index_languages.sparql
- scholia/app/templates/podcast_data.sparql
- scholia/app/views.py
- scholia/scrape/ojs.py
Fixes style issue related to #2426
This was the problem:
```
scholia/scrape/ojs.py:330:80: E501 line too long (81 > 79 characters)
scholia/scrape/ojs.py:339:5: E303 too many blank lines (2)
```
> Fix style issue in Faresh9 title modification

- scholia/app/templates/cito-index_articles-by-year.sparql
- scholia/app/templates/cito-index_statistics.sparql
This patch implements support for CiTO intention annotations from nanopublications. After a [discussion on Mastodon](https://social.edu.nl/@egonw/112011219884262416), there now is a [nanopublication template](https://nanodash.knowledgepixels.com/publish?2&template=https://w3id.org/np/RAX_4tWTyjFpO6nz63s14ucuejd64t2mK3IBlkwZ7jjLo&template-version=latest) for such annotation and a [SPARQL query](https://tinyurl.com/get-cito-nanopubs) can extract this and add this in an automated fashion to Wikidata.
I have [proposed to write a FAIR CookBook recipe](https://github.com/FAIRplus/the-fair-cookbook/issues/628).
None that I can think of. The runtime is still quite fast.
Patch one: The query now adds a "Nanopublication" source (venue), as shown below after "unselecting" the other sources:
Patch …
> Added support for nanopublications as source

- scholia/app/templates/taxon_parent-taxa.sparql
Fixes #2431, #239
Sort the "Parent Taxa" panel from low to high.
> Sort parent ranks

- scholia/app/templates/404-doi.html
- Bypass the DOI detection system of Citation.js to always attempt to query the route parameter as a DOI. E.g. https://scholia.toolforge.org/doi/10.1021/ci040131+
- Same DOI: makes sure HTML cannot be injected, even if it's just `<i>`
- Do not pollute the `c` variable in the global scope
> Fix DOI to QS generation on DOI 404 page

- scholia/text.py
Test on GitHub often fails when trying to setup the data for the text-to-topic function. By reducing the data the error could possibly be avoided.
Fixes #2441
Change LIMIT on text-to-topics query to avoid problem with testing, - and possible other effects.
* `python -m scholia.text text-to-topics-url "schizophrenia"`
> Change LIMIT for text-to-topic query #2441

- scholia/app/templates/dataset.html
Fixes #2421 
Moved the  'details' `<div>` element right after the 'wembedder' `<div>` in `dataset.html` to match the HTML structure of the other templates, the details of the dataset is now appropriately placed like other templates. 
No breaking changes introduced. No new dependencies added.
Tested the updated HTML and the URL is placed perfectly
> Moved the 'details' <div> element right after the 'wembedder' <div> in dataset.html to match the HTML structure of the other templates.

- scholia/app/templates/language-index_works-written-in-the-language.sparql
Table of works in language for language index timed out. This fix uses the Synia query which takes long time, but does not time out.
Fixes #2427
Change the SPARQL query slightly.
* Checked http://127.0.0.1:8100/language
> Fix #2427 language index time out

- scholia/app/templates/event_data.sparql
This add lines with number of participants and acceptance rate to data table on the event aspect.
It was taken from Synia's template:
https://www.wikidata.org/w/index.php?title=Wikidata:Synia:scientificevent&oldid=2126890956
Fixes #2467
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide instructions, so we can reproduce. Please also list any …
> Fix #2467: participants and acceptance

- scholia/app/templates/chemical-index_statistics.sparql
Nothing fancy, just adding the new [P12472](https://www.wikidata.org/wiki/Property:P12472)
> Adding new P12472 to chemical-index_statistics.sparql

- .github/workflows/main.yml
- scholia/app/templates/cito-index_statistics.sparql
Does not fix anything but implements some extra detail of CiTO annotations from nanopublications.
This patch adds two extra statistics lines, resulting in three nanopub related statistics:
* number of nanopublications with CiTO annotations (existing, but better description)
* number of CiTO annotations (new)
* number of articles with CITO annotations defined in nanopubs (new)
None anticipated.
* see the stats table at https://scholia.toolforge.org/cito/
> Further detail of the use of nanopublications for CiTO annotations

- scholia/qs.py
- scholia/utils.py
Letters in DOIs were not uppercased when generating quickstatements.
Fixes #2462
Uppercased DOIs in quickstatements
* http://127.0.0.1:8100/id-to-quickstatements?query=https%3A%2F%2Flink.springer.com%2Fdoi%2F10.1007%2Fs00376-023-3062-1++https%3A%2F%2Fdoi.org%2F10.1073%252Fpnas.2317444121
> Fix #2462 Uppercase DOI in quickstatements

- scholia/qs.py
Now the title property can have up to 1,500 characters. This change was based on @DaxServer #2402 PR
Fixes #2385
Fix long titles not added for OJS, - was an issue for the quickstatement generation.
> Fix #2385 long titles were shorten

- scholia/app/templates/base.html
- scholia/app/templates/check-crossref.html
- scholia/app/templates/disease-curation.html
- scholia/app/templates/gene-curation.html
- scholia/app/templates/protein-curation.html
- scholia/app/templates/q_curation.html
- scholia/app/templates/taxon-curation.html
- scholia/doi.py
Related to #1855
Rebased version of #2342
Note:
- Will probably will need to fix flake and tox errors and will remove the draft status afterwards
- The next PR will add the ability to batch the PRs
Adds support for searching Crossref for the 20 most recent papers on a disease, taxon, gene or protein and sends these results to the tool I've developed to find their presence in Wikidata and creating Quickstatements if they are found
#2337 Adding support for multiple IDs
#2340 Adding support for DOIs to Quickstatements
This PR: Adding a button to curation pages to find if there are recent papers which can be …
> Add ability to find new papers to add to Wikidata via topic curation pages

- scholia/app/templates/author.html
- scholia/app/templates/author_review-statistics.sparql
Now include program committee work
Fixes #2490
Broaden SPARQL query to include program committee work.
* Looked up a couple of researchers.
* Test B
> Fix #2490 Broaden reviewer statistics query

- scholia/app/templates/event.html
- scholia/app/templates/event_data.sparql
Added submissions, accepted, percentage sign and language to data table for event aspect.
Fixes #2493
Added submissions, accepted, percentage sign and language to data table for event aspect.
* http://127.0.0.1:8100/event/Q116958941
> Fix #2493 event data table extension

- requirements.txt
- scholia/query.py
The requirement of the simplejson package is removed The exception class now uses the one from the requests package.
Fixes #2444
Remove dependency on the `simplejson` package
* Ran `tox -r`
> Fix #2444 Remove simplejson package

- scholia/app/static/css/scholia.css
- scholia/app/templates/id-to-quickstatements.html
Rebase of [2345](https://github.com/WDscholia/scholia/pull/2345)
This PR adds the ability to act on many QuickStatements rather than running them individually
* Tested functionality with 10 …
> Add the ability to select a batch of QuickStatements to run

- scholia/app/static/scholia.js
- scholia/app/templates/author-index.html
- scholia/app/templates/base.html
- scholia/app/views.py
- scholia/config.py
- scholia/network.py
- scholia/query.py
- scholia/rss.py
- scholia/scrape/ceurws.py
- scholia/scrape/nips.py
- scholia/scrape/ojs.py
- scholia/text.py
- scholia/wikipedia.py
The setup and reading of the configuration is handle by a separate module.
Fixes #2429
The setup and reading of the configuration is handle by a separate module.
* Various tests on the command-line
* Test for the webapp, e.g., rss
> Fix #2429 config module

- scholia/app/templates/chemical.html
- scholia/app/templates/chemical_biological-processes.sparql
- scholia/app/templates/chemical_found-in-matrix-np.sparql
* http://127.0.0.1:8100/chemical/Q302204
* http://127.0.0.1:8100/chemical/Q128896073
> Adding more info to the `chemical` pages

- scholia/app/templates/author_timeline.sparql
> added birth and death dates to the author timeline
* I've only tested this on https://query.wikidata.org/ , I don't have a full local stack to test on. 
* This is my first contribution to this project and my first SPARQL contribution to any project.
* No changes to python code. Two new stanzas in SPQARL query.
I ran the SPQARL query on https://query.wikidata.org/. the query is too long to use the URL shortener.
* [ X  ] My changes generate no new warnings
* [ X ] I have not used code from external sources without attribution
* [ X ] I have considered [accessibility](https://www.w3.org/standards/webdesign/accessibility) in my implementation 
* [ X ] There are no remaining debug statements (print, console.log, ...)
> added birth and death dates to author timeline

- scholia/app/templates/author_timeline.sparql
Changed death emoji in timeline on author aspect from skull to "Wilting Flower"
Fixes #2532
Changed death emoji in timeline on author aspect from skull to "Wilting Flower"
* http://127.0.0.1:8100/author/Q7085#timeline
> Fix #2532 Change death emoji

- scholia/arxiv.py
- scholia/wikipedia.py
Doctest in arxiv.py failed because of change in error message from the arxiv server. A more general test is now done in the doctest which is not dependent on the specicific error message.
A doctest in wikipedia.py failed because the default requests user agent was banned by the Wikidata Query Service. Now the user agent is set based on the Scholia configuration.
Fixes #2534 and #2535
Please describe the …
> Fix #2534 and #2535 Test in wikipedia and arxiv

- scholia/scrape/ceurws.py
Fixes #2514 
* I ran the command `python -m scholia.scrape.ceurws proceedings-url-to-quickstatements https://ceur-ws.org/Vol-175/` which printed QS statements.
> fix-2514: Fix ceurws scraper where URN is unavailable

- runserver.py
for testing with different backends. This allows starting two servers, with different configurations and in this way, compare the results with two or more different SPARQL endpoint.
This will help port SPARQL queries to SPARQL1.1 and see the impact of the WDQS graph split.
Implements #2540
> Allow setting the port number from the command line

- scholia/app/templates/chemical_biological-processes.sparql
Fixes #2529
Adds the pathway description
Only changes the SPARQL query.
* http://127.0.0.1:8100/chemical/Q302204#biological-processes
> Adds process descriptions

- scholia/app/templates/ask_author_retractions.sparql
- scholia/app/templates/author.html
- scholia/app/templates/author_list-of-retracted-articles.sparql
- scholia/app/templates/author_retracted-articles-per-year.sparql
Fixes #2521
This patch adds a conditional section to the `/author/` aspect. If the author is author of retracted articles, then a 'number of retracted articles' and table with the retracted article gets added to the page. If there are none, nothing is shown.
* Author without retractions: http://127.0.0.1:8100/author/Q20895241
* Author *with* retractions: http://127.0.0.1:8100/author/Q1545025#list-of-retracted-articles
In the latter case, something like this should be visible on the page:
> Lists retracted articles on the author aspect

- scholia/app/templates/organization_page-production.sparql
In the organization aspect the page production query was slow. The new version makes a subquery to identify authors
Fixes #2545
Modify SPARQL query with a WITH subquery
* http://127.0.0.1:8100/organization/Q1269766#page-production - a university
> Fix #2545 Make page production query faster

- scholia/app/static/scholia.js
Now includes a hashmark in the base URL for the Wikidata Query Service.
Fixes #2550
Add hash mark to default parameter
* http://127.0.0.1:8100/author/Q18016466
* http://127.0.0.1:8100/work/
> Fix #2550 Fix WDQS link

- requirements.txt
- scholia/app/templates/work-index_recently-retracted-works.sparql
Fixes #2558 
* CVE-2024-49767
*  CVE-2024-49766
* python -m runserver
> 2558 security issue in werkzeug306

- scholia/app/templates/base.html
- scholia/app/views.py
There are probably a lot of bot requests on Scholia and there is little to index, so to lower the load this change disallow in robots.txt and noindex in meta tag.
- This will not help for malicious bots
- main page and about page could have been exempted
Fixes #2577
Bot load issue
* python runserver.py
* Check meta tag
* Check http://127.0.0.1:8100/robots.txt
> Fix #2577 Disallowing indexing

- scholia/app/templates/location-topic_nearby-researchers.sparql
Nearby researchers table in location-topic aspect had infinite score in some cases.
There was a further problem with the score where a work may have been counted multiple times. This is also fixed
Fixes #2579
Fix in the SPARQL
* http://127.0.0.1:8100/location/Q2239/topic/Q179965
> Fix #2579 Better location-topic score

- scholia/config.py
"Fixes" not using the full data. 
This is not a really a fix, but a workaround offered to us by Wikimedia. cc @bluerasberry
> update to have Scholia use the legacy SPARQL endpoint

- scholia/config.py
Fixes #2593
Match editurl with where the query is run. Previously, it was pointing to the main EP.
The label of the link is unchanged. I just noticed that that label for the same link under `iframe`s says "WDQS legacy full graph" but we do not have any configuration for this, and I suggest to not change that.
> Match editurl with where the query is run

- scholia/app/templates/event_topic-scores.sparql
Fixes #2568
This PR fixes the redirection of topic links in the event panel. Previously, clicking on a topic in the "Topic scores" table of the event aspect would redirect to the *event aspect* instead of the *topic aspect*. This caused confusion and disrupted the expected navigation flow.
**What’s fixed:**
- Modified `event_topic-scores.sparql` so that the topic links correctly redirect to the topic aspect.
- **Before:** Clicking on a topic inside the event panel → redirected to the **event** aspect.
- **After:** Clicking on a topic inside the event panel → correctly redirects to the **topic** aspect.
No visual UI changes; only corrected URL logic.
- None
Manual testing performed:
* Navigated to an event …
> fix: redirect topic links to correct topic aspect in event panel

- scholia/app/static/scholia.js
Fixes #2560
This patch resets the content of the HTML table element, e.g. the `<p`> element with a 'time out' error message. 
It looks that it does the right thing, e.g. for the test page in the bug report.
From the bug report:
* https://scholia.toolforge.org/authors/Q21264190,Q30103188,Q43200797,Q51366847,Q53103589,Q54806715,Q112275836,Q56447936,Q57062249,Q57225833,Q57243435,Q57302902,Q57552918,Q61044058,Q61665725,Q63865447,Q88152670,Q90750787,Q92675346,Q95981554,Q101086361,Q102429134,Q102430988,Q102552081,Q108730193,Q111394757
> Delete the previous content, like a 'time out' error message

- scholia/app/templates/base.html
Fixes #2602
The patch uses the `Intersection Observer API`. For each panel, it creates a unique observer. When a panel becomes visible, the (unique) handler is called. This is followed by an unobserve to ensure that the SPARQL query is run only once.
This browser compability page shows that the `Intersection Observer API` is widely available, but not on old browsers: https://caniuse.com/intersectionobserver
Open up as many pages as possible and see if you see irregularities.
> Lazy loading of table and iframe panels

- scholia/app/templates/dataset.html
No issue reported, because of trivial patch.
The template was still saying "Taxon" but should obviously be "Dataset". With the (relatively) slower server this is now running on, this is more visible.
* Try any dataset in the `dataset` aspect, e.g. https://scholia.toolforge.org/dataset/Q1767082
* Watch the default title `<h1>` previously being Taxon now Dataset, before it gets replaced by the fetched title of the dataset
> The `dataset.html` template still had the 'Taxon' template title

- scholia/app/static/scholia.js
Fixes #2634
It is not clear to me what the problem is, but this patch adds the datatable footer after the table is created.
I have not been able to isolate the problem. It seems related with the lazy loading, but the lazy loading was using the exact same method, so that doesn't make sense to me. The bug report links to #2608, but that patch only is supposed to remove content when the reload functionality is used. So, I can only speculate that that removing of content always happens, and not only when reload was used.
* Open any page
* See the loading in action
* Notice the links in the footer after the results table shows up
> Added the datatable footer

- scholia/app/templates/cito-index_recent-articles.sparql
Fixes #2616 
This patch uses a `SAMPLE()` in the SPARQL query to list articles with explicit CiTO annotation only once.
I put effort in making the query not use `WITH` and is relatively easy to port to QLever.
Cannot think of any.
* Go to [Recent articles with explicit CiTO-annotation](https://scholia.toolforge.org/cito/#recent-articles)
* Check if articles are listed only once (see screenshot in bug report for duplication)
> Reports articles with CiTO annotation only once, and sample the venu

- scholia/app/templates/index.html
Fixes #2612
Replaced the Twitter examples from the front page with ISSN and ROR examples, for eLife and the Wikimedia Foundation, respectively.
Maybe the choice of journal and organisation is inappropriate.
* Go to http://127.0.0.1:8100/
* Test the third column which no longer should show Twitter accounts
> Replaced the Twitter examples with ISSN and ROR

- scholia/app/static/scholia.js
- scholia/app/templates/base.html
Fixes #2630
This patch adds the complementary `sparqlToMatrix2` method that uses the endpoint configuration data. The oldest patch adds the method, the newest uses it.
None that I am aware of. The use seems to be limited to the `author` aspect, which is tested below.
* Go to http://127.0.0.1:8100/author/Q5443996
* Scroll down to `Topics-works matrix`
* Check if the matrix shows up properly
* (Optional) Repeat for other authors)
> Fix sparql to matrix endpoint configuration

- scholia/app/static/scholia.js
- scholia/app/templates/base.html
Fixes #2629 
This patch adds the complementary `askQuery2` method that uses the endpoint configuration data. Similar to the #2631 patch.
The `askQuery()` method is used in the macro defined in `base.html` and that macro is used in three aspects, together four times:
```
$ grep -ri "ask_query_callback" scholia
scholia/app/templates/work.html:{% call ask_query_callback('cito') %}
scholia/app/templates/work.html:{% call ask_query_callback('gallery') %}
scholia/app/templates/venue.html:{% call ask_query_callback('cito') %}
scholia/app/templates/author.html:{% call ask_query_callback('retractions') %}
scholia/app/templates/base.html:{% macro ask_query_callback(panel) -%}
```
Earlier the three aspects are listed …
> Fix askQuery endpoint configuration

- scholia/app/templates/author_list-of-publications.sparql
- scholia/app/templates/organization_recent-literature.sparql
- scholia/app/templates/work_data.sparql
GROUP_CONCAT does not sort, so author lists might be permuted. There seems very little to do about it other than attempt to sort the authors before concatenation and then "hope" that BlazeGraph does the correct sorting. This sometimes work, but at other times there seems to be no effect - at least in recent publication panel for organization the problem persist.
The problem has been noted, e.g., at
https://github.com/w3c/sparql-dev/issues/9
Fixes #2513
This is a partial "hopeful" solution
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your …
> Fix #2513 Attempt to fix author sorting in author list

- tests/test_ask_query.py
Fixes #2652
Query Service URL now read from Scholia configuration
* Test A
* Test B
> Fix #2652 query server URL read from configuration

- scholia/scrape/openreview.py
- tests/test_ask_query.py
Fixes #2651
Extended the OpenReview scraper to also work with PDF URL.
* py.test --doctest-modules scholia/scrape
> 2651 openreview scrape should work with pdf urls

- scholia/arxiv.py
The user-agent was added to the request
Fixes #2659 
API request to arxiv failed. Now the header is submitted with user agent information
* tox -e py310
> Fix #2659 Fix arxiv scraper

- scholia/query.py
Fixes Internal Server Error on redirect.
There is a error when calling Wikidata API from Toolforge but not from another client. Here the is a try-except to catch errors from calling Wikidata API and reading the result, but the fundamental problem is not resolved. It is unclear why the Wikidata API does not work.
The change also changes variables from list to sets to make the code around comparison simpler.
Fixes #2673
Workaround Wikidata API call error
Please describe the [tests](https://numpy.org/doc/stable/reference/testing.html) that you ran to verify your changes. Provide instructions, so we …
> Partial fix #2673 Error handling query call

- scholia/app/templates/chemical-class_identifiers.sparql
- scholia/app/templates/chemical-class_related-chemicals.sparql
Fixes part of https://github.com/WDscholia/scholia/issues/2667
The two queries do not use scholarly information.
Comparison of the Legacy (right) versus Main (left):
The pull request is affected by this bug: https://github.com/WDscholia/scholia/issues/2668
Run the two queries on Legacy and Main. The test fail seems to be due to an unrelated tox test assertion.
For example, when locally testing `/chemical-class/Q41581`, check if you see the two panels use `query.wikidata.org` instead of `query-legacy-full.wikidata.org`:
> Checked two `chemical-class` queries and they can be run on WDQS main

- scholia/app/views.py
Fixes #2703
Adds the global configuration information to the `render_template()` calls.
* Go to http://127.0.0.1:8100/work/
* see 500 results instead of 1
> Aspect landing pages should also use the global configured endpoint info

- scholia/app/templates/retraction_list-of-authors.sparql
It fixes the counting of retracted articles. I forgot to limit the count to retracted articles, so it was accidentally listing the number of articles for that author, including those that are not retracted.
This adds the limiting part of the SPARQL.
* Go to your local https://scholia.toolforge.org/retraction/Q29617959 page
* look up Catherine Verfaillie and make sure it says 4 retracted articles, not 335
> Only count actually retracted articles

- scholia/app/templates/author_list-of-retracted-articles.sparql
Implements item 2 of https://github.com/WDscholia/scholia/issues/2709
Before this patch, the  'retracted articles' panel in the Author aspect linked to the root Scholia folder, for many items in the list, forwarding via the default aspect typing to the /work/ aspect. This patch will update that table to always link to the /retraction/ aspect.
The idea here is that when people link from this table of retracted articles, they are more likely to want to know about why it was retracted. The regular work list (also on the /author/ aspect) continues to link to the regular /work/ aspect. Moreover, from the /retraction/ aspect, users can also go to the /work/ aspect.
Same as https://github.com/WDscholia/scholia/pull/2710: 
> It assumes that that section always exist. The /author/ aspect only …
> The 'retracted articles' panel in the Author aspect now links to the /retraction/ aspect
